# Generated by Django 5.2.17 on 2026-10-01 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0016_analise_custo_compra'),
        ('core', '0075_parametrossistema_balanca_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provedor', models.CharField(default='evolution', max_length=30)),
                ('gateway_url', models.URLField(blank=True, max_length=300)),
                ('api_key_criptografada', models.TextField(blank=True)),
                ('instancia', models.SlugField(max_length=80)),
                ('webhook_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('nao_configurado', 'Não configurado'), ('desconectado', 'Desconectado'), ('aguardando_qr', 'Aguardando QR Code'), ('conectado', 'Conectado'), ('erro', 'Erro')], default='nao_configurado', max_length=24)),
                ('numero_conectado', models.CharField(blank=True, max_length=24)),
                ('nome_conectado', models.CharField(blank=True, max_length=120)),
                ('agente_ativo', models.BooleanField(default=False)),
                ('mensagem_saudacao', models.TextField(default='Olá! Sou o assistente virtual. Posso ajudar você a agendar um serviço.')),
                ('mensagem_transferencia', models.TextField(default='Certo. Vou pausar o atendimento automático para uma pessoa continuar com você.')),
                ('ultima_conexao_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_evento_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
            ],
            options={
                'db_table': 'whatsapp_configuracoes',
            },
        ),
        migrations.CreateModel(
            name='ConversaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_jid', models.CharField(max_length=100)),
                ('telefone', models.CharField(db_index=True, max_length=24)),
                ('nome_contato', models.CharField(blank=True, max_length=150)),
                ('etapa', models.CharField(default='inicio', max_length=40)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('atendimento_humano', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_whatsapp', to='cadastros.cliente')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='whatsapp_agent.configuracaowhatsapp')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
            ],
            options={
                'db_table': 'whatsapp_conversas',
                'ordering': ['-ultima_mensagem_em', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direcao', models.CharField(choices=[('entrada', 'Recebida'), ('saida', 'Enviada')], max_length=10)),
                ('identificador_externo', models.CharField(blank=True, max_length=160)),
                ('tipo', models.CharField(default='texto', max_length=30)),
                ('texto', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('dados_evento', models.JSONField(blank=True, default=dict)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='whatsapp_agent.conversawhatsapp')),
            ],
            options={
                'db_table': 'whatsapp_mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='configuracaowhatsapp',
            constraint=models.UniqueConstraint(fields=('filial',), name='whatsapp_configuracao_filial_unica'),
        ),
        migrations.AddConstraint(
            model_name='configuracaowhatsapp',
            constraint=models.UniqueConstraint(fields=('instancia',), name='whatsapp_instancia_unica'),
        ),
        migrations.AddConstraint(
            model_name='conversawhatsapp',
            constraint=models.UniqueConstraint(fields=('configuracao', 'remote_jid'), name='whatsapp_conversa_remota_unica'),
        ),
        migrations.AddConstraint(
            model_name='mensagemwhatsapp',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador_externo', ''), _negated=True), fields=('conversa', 'identificador_externo'), name='whatsapp_mensagem_externa_unica'),
        ),
    ]
