# Generated by Django 5.2.17 on 2026-10-01 22:23

import django.db.models.deletion
from django.db import migrations, models


def criar_fluxo_padrao(apps, schema_editor):
    Configuracao = apps.get_model('whatsapp_agent', 'ConfiguracaoWhatsApp')
    Menu = apps.get_model('whatsapp_agent', 'MenuWhatsApp')
    Opcao = apps.get_model('whatsapp_agent', 'OpcaoMenuWhatsApp')
    for configuracao in Configuracao.objects.all().iterator():
        menu = Menu.objects.create(
            filial_id=configuracao.filial_id,
            configuracao_id=configuracao.pk,
            codigo='principal',
            nome='Menu principal',
            mensagem='Como posso ajudar?',
            principal=True,
        )
        Opcao.objects.bulk_create([
            Opcao(menu_id=menu.pk, chave='1', titulo='Fazer um agendamento', acao='agenda', ordem=0),
            Opcao(
                menu_id=menu.pk, chave='2', titulo='Falar com um atendente',
                acao='atendimento_humano',
                palavras_chave='atendente, humano, pessoa, falar com atendente', ordem=1,
            ),
            Opcao(
                menu_id=menu.pk, chave='3', titulo='Encerrar a conversa', acao='encerrar',
                palavras_chave='encerrar, finalizar, sair', ordem=2,
            ),
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_parametrossistema_balanca_ean'),
        ('whatsapp_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='mensagem_encerramento',
            field=models.TextField(default='Conversa encerrada. Obrigado pelo contato! 👋\nQuando precisar, envie *oi* para começar novamente.'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='mensagem_opcao_invalida',
            field=models.TextField(default='Não entendi essa opção.'),
        ),
        migrations.CreateModel(
            name='MenuWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=60)),
                ('nome', models.CharField(max_length=80)),
                ('mensagem', models.TextField(default='Como posso ajudar?')),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='whatsapp_agent.configuracaowhatsapp')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
            ],
            options={
                'db_table': 'whatsapp_menus',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoMenuWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chave', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('acao', models.CharField(choices=[('agenda', 'Enviar link da agenda'), ('atendimento_humano', 'Transferir para atendente'), ('mensagem', 'Enviar uma mensagem'), ('abrir_menu', 'Abrir outro menu'), ('menu_principal', 'Voltar ao menu principal'), ('encerrar', 'Encerrar conversa')], max_length=32)),
                ('mensagem', models.TextField(blank=True)),
                ('palavras_chave', models.TextField(blank=True, help_text='Palavras alternativas separadas por vírgula ou uma por linha.')),
                ('voltar_ao_menu', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='whatsapp_agent.menuwhatsapp')),
                ('menu_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp_agent.menuwhatsapp')),
            ],
            options={
                'db_table': 'whatsapp_menu_opcoes',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='menuwhatsapp',
            constraint=models.UniqueConstraint(fields=('configuracao', 'codigo'), name='whatsapp_menu_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='opcaomenuwhatsapp',
            constraint=models.UniqueConstraint(fields=('menu', 'chave'), name='whatsapp_opcao_chave_unica'),
        ),
        migrations.RunPython(criar_fluxo_padrao, migrations.RunPython.noop),
    ]
