# Generated by Django 5.2.17 on 2026-10-08 14:58

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0005_crm_e_recuperacao_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsAppCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instancia', models.SlugField(default='ited-central-dashboard', max_length=80, unique=True)),
                ('webhook_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('nao_configurado', 'Não configurado'), ('desconectado', 'Desconectado'), ('aguardando_qr', 'Aguardando QR Code'), ('conectado', 'Conectado'), ('erro', 'Erro')], default='nao_configurado', max_length=24)),
                ('numero_conectado', models.CharField(blank=True, max_length=24)),
                ('nome_conectado', models.CharField(blank=True, max_length=120)),
                ('resumos_ativos', models.BooleanField(default=False, help_text='Ativa a preparação automática dos resumos diários.')),
                ('horario_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('horario_fim', models.TimeField(default=datetime.time(18, 0))),
                ('intervalo_entre_envios_minutos', models.PositiveSmallIntegerField(default=3, help_text='Uma mensagem por vez, respeitando este intervalo mínimo.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('limite_diario', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('max_tentativas', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mensagem_resumo', models.TextField(default='📊 *Resumo diário — {filial}*\n🗓️ {data}\n\n💰 *Vendas:* {vendas}\n💵 *Recebido:* {recebido}\n🧾 *Quantidade de vendas:* {quantidade_vendas}\n🎯 *Ticket médio:* {ticket_medio}\n🏷️ *Descontos:* {descontos}\n↩️ *Cancelamentos:* {cancelamentos}\n\n⚠️ *Estoque crítico:* {estoque_critico}\n⏳ *Produtos próximos do vencimento:* {vencimentos}\n📌 *Contas a receber vencidas:* {contas_vencidas}\n📈 *Comparação com o dia anterior:* {comparacao}{agenda}', help_text='Variáveis: {empresa}, {filial}, {data}, {vendas}, {recebido}, {quantidade_vendas}, {ticket_medio}, {descontos}, {cancelamentos}, {estoque_critico}, {vencimentos}, {contas_vencidas}, {comparacao} e {agenda}.')),
                ('ultima_conexao_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_envio_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_evento_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'whatsapp_configuracao_central',
            },
        ),
        migrations.CreateModel(
            name='EnvioResumoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_alias', models.SlugField(blank=True, default='default', max_length=80)),
                ('empresa_nome', models.CharField(max_length=150)),
                ('filial_nome', models.CharField(max_length=150)),
                ('filial_cnpj', models.CharField(max_length=14)),
                ('destinatario_nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=13)),
                ('data_referencia', models.DateField(db_index=True)),
                ('metricas', models.JSONField(default=dict)),
                ('mensagem', models.TextField()),
                ('agendado_para', models.DateTimeField(db_index=True)),
                ('disparo_manual', models.BooleanField(default=False, help_text='Permite iniciar este envio fora da janela da rotina automática.')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=16)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('identificador_externo', models.CharField(blank=True, max_length=160)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='whatsapp_agent.configuracaowhatsappcentral')),
            ],
            options={
                'db_table': 'whatsapp_envios_resumo',
                'ordering': ['-data_referencia', 'agendado_para', 'id'],
                'indexes': [models.Index(fields=['status', 'agendado_para'], name='whatsapp_en_status_e37156_idx'), models.Index(fields=['tenant_alias', 'filial_cnpj', 'data_referencia'], name='whatsapp_en_tenant__c8a240_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_alias', 'filial_cnpj', 'telefone', 'data_referencia'), name='whatsapp_resumo_filial_destino_dia_unico')],
            },
        ),
    ]
