# Generated by Django 5.2.17 on 2026-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0007_catalogo_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='modo_atendimento',
            field=models.CharField(choices=[('agenda', 'Somente agendamento'), ('catalogo', 'Somente catálogo e pedidos'), ('ambos', 'Agendamento e catálogo')], default='agenda', max_length=16),
        ),
    ]
