# Generated by Django 5.2.17 on 2026-10-08 22:30

from django.db import migrations, models


MENSAGEM_ANTIGA = (
    '🛒 *Revise seu pedido {numero}*\n\n'
    '{itens}\n\n'
    '*Subtotal:* {subtotal}\n'
    '*Frete:* {frete}\n'
    '*Total:* {total}\n'
    '*Recebimento:* {entrega}\n'
    '*Pagamento:* {pagamento}\n'
    '*Observação:* {observacao}\n\n'
    '*1.* Confirmar pedido\n'
    '*2.* Refazer pedido\n'
    '*3.* Cancelar'
)
MENSAGEM_NOVA = (
    '✅ *Pedido confirmado {numero}*\n\n'
    '{itens}\n\n'
    '*Subtotal:* {subtotal}\n'
    '*Frete:* {frete}\n'
    '*Total:* {total}\n'
    '*Recebimento:* {entrega}\n'
    '*Pagamento:* {pagamento}\n'
    '*Observação:* {observacao}'
)


def atualizar_mensagem_padrao(apps, schema_editor):
    ConfiguracaoWhatsApp = apps.get_model('whatsapp_agent', 'ConfiguracaoWhatsApp')
    ConfiguracaoWhatsApp.objects.filter(
        mensagem_resumo_pedido=MENSAGEM_ANTIGA,
    ).update(mensagem_resumo_pedido=MENSAGEM_NOVA)


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_agent', '0008_configuracaowhatsapp_modo_atendimento'),
    ]

    operations = [
        migrations.RunPython(atualizar_mensagem_padrao, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='configuracaowhatsapp',
            name='mensagem_resumo_pedido',
            field=models.TextField(default='✅ *Pedido confirmado {numero}*\n\n{itens}\n\n*Subtotal:* {subtotal}\n*Frete:* {frete}\n*Total:* {total}\n*Recebimento:* {entrega}\n*Pagamento:* {pagamento}\n*Observação:* {observacao}', help_text='Variáveis: {numero}, {nome}, {itens}, {subtotal}, {frete}, {total}, {entrega}, {pagamento} e {observacao}.'),
        ),
    ]
