# Generated by Django 5.2.17 on 2026-08-27 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
"""
Viagem, carga por produto e saldo em poder de quem viaja.

AS RENOMEACOES DE INDICE FORAM RETIRADAS desta migration. O app tem seis
`RenameIndex` pendentes de antes desta tarefa, e o `makemigrations` as
empacotou junto por estarem na fila. Sao DDL de outra pessoa: aplicar aqui
faria esta migration mexer no que nao e' dela, e um `RENAME INDEX` que falhe
derruba o release inteiro. Continuam pendentes, como estavam.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_funcionario"),
        ("core", "0054_food_service_so_padaria"),
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("fiscal", "0008_naturezas_de_operacao"),
        ("logistica", "0015_acentos_nos_rotulos_do_manifesto"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        ("vendas", "0002_compat_legacy_required_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "peso_kg",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("observacao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Item da carga",
                "verbose_name_plural": "Itens da carga",
                "db_table": "logistica_itens_carga",
                "ordering": ["viagem", "natureza", "produto", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SaldoCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantidade_remetida",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "quantidade_vendida",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "quantidade_bonificada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "quantidade_retornada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "quantidade_baixada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
            ],
            options={
                "verbose_name": "Saldo em poder da viagem",
                "verbose_name_plural": "Saldos em poder da viagem",
                "db_table": "logistica_saldos_carga",
                "ordering": ["viagem", "produto"],
            },
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "data_saida",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("data_retorno", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejamento", "Em planejamento"),
                            ("em_rota", "Em rota"),
                            ("em_conferencia", "Em conferência"),
                            ("encerrada", "Encerrada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="planejamento",
                        max_length=20,
                    ),
                ),
                ("motorista_nome", models.CharField(blank=True, max_length=120)),
                ("motorista_documento", models.CharField(blank=True, max_length=30)),
                ("veiculo_placa", models.CharField(blank=True, max_length=10)),
                ("veiculo_descricao", models.CharField(blank=True, max_length=100)),
                ("rota", models.CharField(blank=True, max_length=160)),
                ("uf_origem", models.CharField(blank=True, max_length=2)),
                ("uf_destino", models.CharField(blank=True, max_length=2)),
                (
                    "percurso_ufs",
                    models.CharField(
                        blank=True,
                        help_text="UFs por onde o veículo passa, na ordem, separadas por vírgula.",
                        max_length=120,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
                "db_table": "logistica_viagens",
                "ordering": ["-data_saida", "-numero"],
            },
        ),
        migrations.AddField(
            model_name="itemcarga",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_carga",
                to="cadastros.cliente",
            ),
        ),
        migrations.AddField(
            model_name="itemcarga",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_carga",
                to="estoque.loteproduto",
            ),
        ),
        migrations.AddField(
            model_name="itemcarga",
            name="natureza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_carga",
                to="fiscal.naturezaoperacao",
            ),
        ),
        migrations.AddField(
            model_name="itemcarga",
            name="pedido_venda",
            field=models.ForeignKey(
                blank=True,
                help_text="O pedido que esta linha atende, quando a venda já existia.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_carga",
                to="vendas.pedidovenda",
            ),
        ),
        migrations.AddField(
            model_name="itemcarga",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_carga",
                to="produtos.produto",
            ),
        ),
        migrations.AddField(
            model_name="saldocarga",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saldos_carga",
                to="estoque.loteproduto",
            ),
        ),
        migrations.AddField(
            model_name="saldocarga",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="saldos_carga",
                to="produtos.produto",
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="filial",
            field=models.ForeignKey(
                help_text="Filial proprietária do registro",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.filial",
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viagens_responsavel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="transportadora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viagens",
                to="cadastros.transportadora",
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                help_text="Quem responde pela mercadoria que sai sem comprador.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viagens_vendedor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saldocarga",
            name="viagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saldos",
                to="logistica.viagem",
            ),
        ),
        migrations.AddField(
            model_name="itemcarga",
            name="viagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="logistica.viagem",
            ),
        ),
        migrations.AddField(
            model_name="mdfe",
            name="viagem",
            field=models.ForeignKey(
                blank=True,
                help_text="A viagem que este manifesto ampara. Um MDF-e por viagem.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mdfes",
                to="logistica.viagem",
            ),
        ),
        migrations.AddField(
            model_name="romaneiocarga",
            name="viagem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="romaneios",
                to="logistica.viagem",
            ),
        ),
        migrations.AddIndex(
            model_name="viagem",
            index=models.Index(
                fields=["filial", "status", "data_saida"],
                name="logistica_v_filial__fdd4a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="viagem",
            index=models.Index(
                fields=["filial", "vendedor", "status"],
                name="logistica_v_filial__67abe8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="viagem",
            constraint=models.UniqueConstraint(
                fields=("filial", "numero"), name="viagem_numero_por_filial"
            ),
        ),
        migrations.AddIndex(
            model_name="saldocarga",
            index=models.Index(
                fields=["viagem", "produto"], name="logistica_s_viagem__ecb98f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="saldocarga",
            constraint=models.UniqueConstraint(
                fields=("viagem", "produto", "lote"),
                name="saldo_carga_unico_por_produto_lote",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcarga",
            index=models.Index(
                fields=["viagem", "natureza"], name="logistica_i_viagem__a8a174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemcarga",
            index=models.Index(
                fields=["viagem", "produto"], name="logistica_i_viagem__087ffc_idx"
            ),
        ),
    ]
