# Generated by Django 5.2.17 on 2026-08-27 22:06

import django.db.models.deletion
"""
O ciclo de vida da viagem, com as etapas que a operacao tem de verdade.

Sem as seis `RenameIndex` que o `makemigrations` empacota junto: sao DDL
pendente de antes desta tarefa, e nao cabe a esta migration aplica-las.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_funcionario"),
        ("logistica", "0016_viagem_e_carga"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem",
            name="hora_saida",
            field=models.TimeField(
                blank=True,
                help_text="A hora em que o veículo deixa a empresa.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="motorista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viagens",
                to="cadastros.motorista",
            ),
        ),
        migrations.AddField(
            model_name="viagem",
            name="previsao_retorno",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="viagem",
            name="veiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viagens",
                to="cadastros.veiculo",
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="data_retorno",
            field=models.DateField(
                blank=True, help_text="Quando o veículo efetivamente voltou.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("em_preparacao", "Em preparação"),
                    ("aguardando_documentos", "Aguardando documentos fiscais"),
                    ("documentos_emitidos", "Documentos emitidos"),
                    ("mdfe_autorizado", "MDF-e autorizado"),
                    ("em_transito", "Em trânsito"),
                    ("em_vendas", "Em vendas"),
                    ("retornando", "Retornando"),
                    ("aguardando_conferencia", "Aguardando conferência"),
                    ("finalizada", "Finalizada"),
                    ("cancelada", "Cancelada"),
                ],
                db_index=True,
                default="rascunho",
                max_length=30,
            ),
        ),
    ]
