# Generated by Django 5.2.17 on 2026-08-27 22:40

import django.db.models.deletion
"""
O elo entre a linha da carga e a nota que a ampara.

Sem as `RenameIndex` que o `makemigrations` empacota junto: DDL pendente de
antes desta tarefa.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_funcionario"),
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("financeiro", "0055_formas_pagamento_padrao_das_filiais"),
        ("fiscal", "0008_naturezas_de_operacao"),
        ("logistica", "0017_viagem_ciclo_de_vida"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        ("vendas", "0002_compat_legacy_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcarga",
            name="documento_fiscal",
            field=models.ForeignKey(
                blank=True,
                help_text="A nota que ampara esta linha, quando já emitida.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_carga",
                to="financeiro.documentofiscal",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcarga",
            index=models.Index(
                fields=["pedido_venda"], name="logistica_i_pedido__e4eabd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemcarga",
            index=models.Index(
                fields=["documento_fiscal"], name="logistica_i_documen_2cb9f4_idx"
            ),
        ),
    ]
