# Generated by Django 5.2.17 on 2026-08-27 23:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
"""
As vendas feitas na rua, contra o saldo que a viagem carrega.

Sem as `RenameIndex` que o `makemigrations` empacota junto: DDL pendente de
antes desta tarefa.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_funcionario"),
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("financeiro", "0055_formas_pagamento_padrao_das_filiais"),
        ("logistica", "0018_item_carga_documento_fiscal"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemVendaViagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "verbose_name": "Item da venda em viagem",
                "verbose_name_plural": "Itens da venda em viagem",
                "db_table": "logistica_itens_venda_viagem",
                "ordering": ["venda", "pk"],
            },
        ),
        migrations.CreateModel(
            name="VendaViagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "data",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registrada", "Registrada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="registrada",
                        max_length=20,
                    ),
                ),
                ("cliente_nome", models.CharField(max_length=180)),
                ("cliente_documento", models.CharField(blank=True, max_length=20)),
                ("endereco", models.JSONField(blank=True, default=dict)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("observacao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Venda durante a viagem",
                "verbose_name_plural": "Vendas durante a viagem",
                "db_table": "logistica_vendas_viagem",
                "ordering": ["-data", "-numero"],
            },
        ),
        migrations.AddField(
            model_name="itemvendaviagem",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_venda_viagem",
                to="estoque.loteproduto",
            ),
        ),
        migrations.AddField(
            model_name="itemvendaviagem",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_venda_viagem",
                to="produtos.produto",
            ),
        ),
        migrations.AddField(
            model_name="vendaviagem",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_viagem",
                to="cadastros.cliente",
            ),
        ),
        migrations.AddField(
            model_name="vendaviagem",
            name="condicao_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_viagem",
                to="financeiro.condicaopagamento",
            ),
        ),
        migrations.AddField(
            model_name="vendaviagem",
            name="documento_fiscal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_viagem",
                to="financeiro.documentofiscal",
            ),
        ),
        migrations.AddField(
            model_name="vendaviagem",
            name="forma_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_viagem",
                to="financeiro.formapagamento",
            ),
        ),
        migrations.AddField(
            model_name="vendaviagem",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_viagem",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendaviagem",
            name="viagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendas",
                to="logistica.viagem",
            ),
        ),
        migrations.AddField(
            model_name="itemvendaviagem",
            name="venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="logistica.vendaviagem",
            ),
        ),
        migrations.AddIndex(
            model_name="vendaviagem",
            index=models.Index(
                fields=["viagem", "status"], name="logistica_v_viagem__85bd84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendaviagem",
            index=models.Index(
                fields=["cliente"], name="logistica_v_cliente_37a1d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendaviagem",
            constraint=models.UniqueConstraint(
                fields=("viagem", "numero"), name="venda_viagem_numero_por_viagem"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvendaviagem",
            index=models.Index(
                fields=["venda", "produto"], name="logistica_i_venda_i_d38cc3_idx"
            ),
        ),
    ]
