"""
O acompanhamento da entrega de uma bonificacao, e a prova de que chegou.

Mercadoria vendida cobra a si mesma: se nao chegar, o cliente liga. A
bonificacao nao -- ninguem pagou por ela, ninguem reclama, e ela e' exatamente
a que some no caminho sem que nada acuse.
"""
# Generated by Django 6.0.4 on 2026-08-28 01:41

import apps.logistica.models_bonificacao
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0023_bonificacao_nao_e_venda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprovanteBonificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("foto", "Foto"),
                            ("assinatura", "Assinatura"),
                            ("comprovante", "Comprovante"),
                            ("canhoto", "Canhoto"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=apps.logistica.models_bonificacao.caminho_do_comprovante
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=160)),
                ("enviado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Comprovante de bonificação",
                "verbose_name_plural": "Comprovantes de bonificação",
                "db_table": "logistica_comprovantes_bonificacao",
                "ordering": ["enviado_em"],
            },
        ),
        migrations.CreateModel(
            name="EntregaBonificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_transporte", "Em transporte"),
                            ("entregue", "Entregue"),
                            ("recusada", "Recusada"),
                            ("cancelada", "Cancelada"),
                            ("retorno_pendente", "Retorno pendente"),
                            ("retornada", "Retornada"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("entregue_em", models.DateTimeField(blank=True, null=True)),
                (
                    "quantidade_entregue",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "destinatario_nome",
                    models.CharField(
                        blank=True,
                        help_text="Quem recebeu — é ele que responde por ter recebido.",
                        max_length=120,
                    ),
                ),
                ("destinatario_documento", models.CharField(blank=True, max_length=30)),
                ("observacao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Entrega de bonificação",
                "verbose_name_plural": "Entregas de bonificação",
                "db_table": "logistica_entregas_bonificacao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="comprovantebonificacao",
            name="enviado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comprovantes_bonificacao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entregabonificacao",
            name="entrega_rua",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acompanhamento",
                to="logistica.vendaviagem",
            ),
        ),
        migrations.AddField(
            model_name="entregabonificacao",
            name="entregue_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bonificacoes_entregues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entregabonificacao",
            name="item_carga",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrega_bonificacao",
                to="logistica.itemcarga",
            ),
        ),
        migrations.AddField(
            model_name="comprovantebonificacao",
            name="entrega",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comprovantes",
                to="logistica.entregabonificacao",
            ),
        ),
        migrations.AddIndex(
            model_name="entregabonificacao",
            index=models.Index(fields=["status"], name="logistica_e_status_fa9782_idx"),
        ),
        migrations.AddConstraint(
            model_name="entregabonificacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entrega_rua__isnull", True), ("item_carga__isnull", False)
                    ),
                    models.Q(
                        ("entrega_rua__isnull", False), ("item_carga__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="bonificacao_tem_uma_origem",
            ),
        ),
        migrations.AddIndex(
            model_name="comprovantebonificacao",
            index=models.Index(
                fields=["entrega", "tipo"], name="logistica_c_entrega_ee3ffe_idx"
            ),
        ),
    ]
