"""
A bonificacao que nao chegou passa a dizer POR QUE.

Sem motivo, "nao entregue" e' um numero em relatorio. Com ele, e' um
problema com dono: "cliente ausente" e' roteiro errado; "produto
danificado" e' carregamento errado -- e os dois se resolvem em lugares
diferentes.

Nasce VAZIO para o que ja' existe: escolher um motivo retroativo seria
inventar a razao de quem estava na porta do cliente.
"""
# Generated by Django 6.0.4 on 2026-08-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0024_entrega_da_bonificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregabonificacao",
            name="motivo_nao_entrega",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ausente", "Cliente ausente"),
                    ("recusou", "Cliente recusou"),
                    ("danificado", "Produto danificado"),
                    ("quantidade", "Erro de quantidade"),
                    ("cancelamento", "Cancelamento"),
                    ("outro", "Outro"),
                ],
                db_index=True,
                help_text="Por que a bonificação não foi entregue.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entregabonificacao",
            name="nao_entregue_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entregabonificacao",
            name="retorno_tratado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando a mercadoria voltou de fato ao estoque ou ao saldo.",
                null=True,
            ),
        ),
    ]
