"""
Os status do MDF-e passam a usar o vocabulario de quem opera.

So' os ROTULOS mudam -- rascunho vira "Nao emitido", aguardando_nfe vira
"Aguardando emissao", processando vira "Enviando". Os valores continuam os
mesmos: troca-los exigiria migrar dado e reescrever consulta em meia duzia
de lugares para ganhar nada, porque quem le a tela le o rotulo.
"""
# Generated by Django 6.0.4 on 2026-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0025_bonificacao_nao_entregue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mdfe",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Não emitido"),
                    ("aguardando_nfe", "Aguardando emissão"),
                    ("processando", "Enviando"),
                    ("autorizado", "Autorizado"),
                    ("rejeitado", "Rejeitado"),
                    ("encerrado", "Encerrado"),
                    ("cancelado", "Cancelado"),
                ],
                db_index=True,
                default="rascunho",
                max_length=20,
            ),
        ),
    ]
