# Generated by Django 6.0.4 on 2026-08-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0013_movimentacao_cliente"),
        ("logistica", "0026_rotulos_do_mdfe"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcarga",
            name="movimentacao",
            field=models.ForeignKey(
                blank=True,
                help_text="A baixa de estoque que esta linha gerou.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_carga",
                to="estoque.movimentacaoestoque",
            ),
        ),
    ]
