# Generated by Django 6.0.4 on 2026-08-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0027_movimentacao_da_linha_da_carga"),
        ("vendas", "0002_compat_legacy_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoexpedicao",
            name="pedido_venda",
            field=models.ForeignKey(
                blank=True,
                help_text="Pedido de venda que originou esta expedição, quando houver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_expedicao",
                to="vendas.pedidovenda",
            ),
        ),
    ]
