# Generated by Django 6.0.4 on 2026-08-28 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0028_pedido_de_venda_na_expedicao"),
        ("vendas", "0002_compat_legacy_required_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedidoexpedicao",
            name="item_venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_expedicao",
                to="vendas.itempedidovenda",
            ),
        ),
    ]
