# Generated by Django 6.0.4 on 2026-08-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0056_payload_do_documento"),
        ("logistica", "0029_item_da_venda_na_expedicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemromaneiocarga",
            name="pedido_expedicao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entregas_romaneio",
                to="logistica.pedidoexpedicao",
            ),
        ),
        migrations.AddField(
            model_name="pedidoexpedicao",
            name="condicao_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_expedicao",
                to="financeiro.condicaopagamento",
            ),
        ),
        migrations.AddField(
            model_name="pedidoexpedicao",
            name="forma_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_expedicao",
                to="financeiro.formapagamento",
            ),
        ),
    ]
