# Generated by Django 6.0.4 on 2026-09-07 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0030_cobranca_e_entrega_da_expedicao"),
        ("pdv", "0019_venda_bonificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoexpedicao",
            name="venda_pdv",
            field=models.ForeignKey(
                blank=True,
                help_text="Venda do PDV (com NF-e) que originou esta expedição, quando houver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_expedicao",
                to="pdv.vendapdv",
            ),
        ),
    ]
