# Generated by Django 6.0.4 on 2026-08-25 15:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0015_funcionario"),
        ("core", "0051_alerta_cliente_ajuste"),
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(db_index=True, max_length=80)),
                (
                    "variedade",
                    models.CharField(
                        blank=True,
                        help_text="Tommy, Palmer, Espada… muda o rendimento e o Brix.",
                        max_length=60,
                    ),
                ),
                (
                    "brix_minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sólidos solúveis mínimos. Abaixo disso a fruta está verde.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ph_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Acima disso a acidez não protege o produto.",
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "impureza_maxima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% de folha, galho e terra tolerada na carga.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rendimento_esperado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% de polpa que sai da fruta limpa. Ex.: manga ≈ 60%.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "safra_inicio",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "safra_fim",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        null=True,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item do catálogo que representa esta fruta in natura.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frutas_polpa",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fruta",
                "verbose_name_plural": "Frutas",
                "db_table": "polpa_frutas",
                "ordering": ["nome", "variedade"],
            },
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                ("data", models.DateField(db_index=True)),
                ("hora_chegada", models.TimeField(blank=True, null=True)),
                ("placa", models.CharField(blank=True, max_length=10)),
                ("motorista", models.CharField(blank=True, max_length=80)),
                ("nota_fiscal", models.CharField(blank=True, max_length=20)),
                (
                    "peso_bruto",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="kg, com o veículo.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tara",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="kg do veículo e das caixas.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "desconto_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="kg descontados por impureza, fruta podre ou excesso de água.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "temperatura_chegada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C da fruta na chegada.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "brix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "acidez",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="% de ácido cítrico.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "impureza",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% de folha, galho e terra.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "danificada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% de fruta batida ou podre.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("classificado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "preco_kg",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="R$ por kg líquido pago ao produtor.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pesagem", "Em pesagem"),
                            ("classificacao", "Aguardando classificação"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="pesagem",
                        max_length=15,
                    ),
                ),
                ("motivo_recusa", models.TextField(blank=True)),
                ("decidido_em", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "classificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classificacoes_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recebimentos_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisoes_recebimento_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "fruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recebimentos",
                        to="polpa.fruta",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote de matéria-prima criado quando a carga foi aprovada.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recebimentos_polpa",
                        to="estoque.loteproduto",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recebimentos_polpa",
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recebimento de fruta",
                "verbose_name_plural": "Recebimentos de fruta",
                "db_table": "polpa_recebimentos",
                "ordering": ["-data", "-numero"],
            },
        ),
        migrations.AddIndex(
            model_name="fruta",
            index=models.Index(
                fields=["filial", "ativo"], name="polpa_fruta_filial__8cc27a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fruta",
            unique_together={("filial", "nome", "variedade")},
        ),
        migrations.AddIndex(
            model_name="recebimento",
            index=models.Index(
                fields=["filial", "status"], name="polpa_receb_filial__795099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recebimento",
            index=models.Index(
                fields=["filial", "data"], name="polpa_receb_filial__f4bb1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recebimento",
            index=models.Index(
                fields=["fruta", "data"], name="polpa_receb_fruta_i_871947_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recebimento",
            unique_together={("filial", "numero")},
        ),
    ]
