# Generated by Django 6.0.4 on 2026-08-25 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alerta_cliente_ajuste"),
        ("polpa", "0001_initial"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("materia_prima", "Matéria-prima"),
                            ("embalagem", "Material de embalagem"),
                            ("acabado", "Produto acabado"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fruta", "Fruta in natura"),
                            ("polpa_base", "Polpa-base"),
                            ("acai_base", "Açaí (base)"),
                            ("acucar", "Açúcar"),
                            ("agua", "Água"),
                            ("leite", "Leite"),
                            ("leite_po", "Leite em pó"),
                            ("creme_leite", "Creme de leite"),
                            ("gordura", "Gordura"),
                            ("estabilizante", "Estabilizante"),
                            ("emulsificante", "Emulsificante"),
                            ("aroma", "Aroma"),
                            ("corante", "Corante"),
                            ("conservante", "Conservante"),
                            ("ingrediente", "Outro ingrediente"),
                            ("saco", "Saco"),
                            ("pote", "Pote"),
                            ("copo", "Copo"),
                            ("tampa", "Tampa"),
                            ("caixa", "Caixa"),
                            ("filme", "Filme plástico"),
                            ("etiqueta", "Etiqueta"),
                            ("fardo", "Fardo"),
                            ("pallet", "Pallet"),
                            ("polpa", "Polpa de fruta"),
                            ("acai", "Açaí"),
                            ("sorvete", "Sorvete"),
                            ("picole", "Picolé"),
                            ("creme", "Creme / base congelada"),
                            ("fruta_congelada", "Fruta congelada"),
                            ("mix", "Mix de frutas"),
                            ("personalizado", "Produto sob formulação"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "sabor",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Manga, açaí com guaraná, morango…",
                        max_length=60,
                    ),
                ),
                (
                    "volume_ml",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volume da embalagem em ml, quando o produto é líquido.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "validade_dias",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Prazo de validade do produto, em dias a partir da fabricação.",
                        null=True,
                    ),
                ),
                (
                    "caixas_por_pallet",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Quantas caixas fecham um pallet — a conta da expedição.",
                        null=True,
                    ),
                ),
                (
                    "registro_mapa",
                    models.CharField(
                        blank=True,
                        help_text="Registro no MAPA/SIF, quando o produto exige.",
                        max_length=40,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "fruta",
                    models.ForeignKey(
                        blank=True,
                        help_text="A fruta deste item, quando ela tem ficha de recebimento.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="polpa.fruta",
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha_polpa",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha de produto",
                "verbose_name_plural": "Fichas de produto",
                "db_table": "polpa_fichas_produto",
                "ordering": ["produto__descricao"],
                "indexes": [
                    models.Index(
                        fields=["filial", "classe"],
                        name="polpa_ficha_filial__2d807c_idx",
                    ),
                    models.Index(
                        fields=["filial", "tipo"], name="polpa_ficha_filial__853985_idx"
                    ),
                ],
            },
        ),
    ]
