# Generated by Django 6.0.4 on 2026-08-25 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alerta_cliente_ajuste"),
        ("polpa", "0002_ficha_de_produto"),
        ("producao", "0003_alter_perdaproducao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rendimento_esperado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% do que entra que vira produto. Ex.: manga ≈ 60%.",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "temperatura_processo_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "temperatura_processo_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "observacoes_tecnicas",
                    models.TextField(
                        blank=True,
                        help_text="O que quem opera precisa saber e não cabe numa etapa.",
                    ),
                ),
                (
                    "ficha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receita_polpa",
                        to="producao.fichatecnica",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "db_table": "polpa_receitas",
                "ordering": ["ficha__produto_acabado", "-ficha__versao"],
            },
        ),
        migrations.CreateModel(
            name="EtapaReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="A sequência importa: sanitizar depois de despolpar não sanitiza.",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                (
                    "equipamento",
                    models.CharField(
                        blank=True,
                        help_text="Despolpadeira, pasteurizador, envasadora, túnel…",
                        max_length=80,
                    ),
                ),
                (
                    "tempo_minutos",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duração estimada desta etapa.", null=True
                    ),
                ),
                (
                    "temperatura_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "temperatura_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "perda_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="% do que entra nesta etapa que se perde nela.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("instrucao", models.TextField(blank=True)),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="polpa.receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa da receita",
                "verbose_name_plural": "Etapas da receita",
                "db_table": "polpa_etapas_receita",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
