# Generated by Django 6.0.4 on 2026-08-25 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alerta_cliente_ajuste"),
        ("polpa", "0003_receita"),
        ("producao", "0003_alter_perdaproducao_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemPolpa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("liberada", "Liberada"),
                            ("em_producao", "Em produção"),
                            ("pausada", "Pausada"),
                            ("qualidade", "Em controle de qualidade"),
                            ("produzida", "Produzida"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="planejada",
                        max_length=15,
                    ),
                ),
                ("pausada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "motivo_pausa",
                    models.CharField(
                        blank=True,
                        help_text="Acabou a fruta, quebrou a despolpadeira, faltou embalagem…",
                        max_length=160,
                    ),
                ),
                (
                    "minutos_parados",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Soma das pausas — o tempo que a linha ficou parada.",
                    ),
                ),
                ("enviada_qualidade_em", models.DateTimeField(blank=True, null=True)),
                ("liberada_qualidade_em", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "ordem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polpa",
                        to="producao.ordemproducao",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="polpa.receita",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quem responde por esta produção.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de produção",
                "verbose_name_plural": "Ordens de produção",
                "db_table": "polpa_ordens",
                "ordering": ["-ordem__created_at"],
                "indexes": [
                    models.Index(
                        fields=["filial", "situacao"],
                        name="polpa_orden_filial__f34205_idx",
                    )
                ],
            },
        ),
    ]
