# Generated by Django 6.0.4 on 2026-08-25 17:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alerta_cliente_ajuste"),
        ("polpa", "0004_ordem_producao"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(db_index=True, max_length=80)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("linha", "Linha de produção"),
                            ("maquina", "Máquina"),
                        ],
                        default="linha",
                        max_length=10,
                    ),
                ),
                (
                    "capacidade_dia",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Quanto este recurso produz num dia, na unidade do produto.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "horas_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8"),
                        help_text="Horas disponíveis por dia — o turno.",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "setup_minutos",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Tempo de troca entre produções (higienização, troca de sabor).",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "linha_producao",
                    models.ForeignKey(
                        blank=True,
                        help_text="Liga à linha do ERP, quando ela já existe.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recursos_polpa",
                        to="produtos.linhaproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso de produção",
                "verbose_name_plural": "Recursos de produção",
                "db_table": "polpa_recursos",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.AddField(
            model_name="ordempolpa",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordens",
                to="polpa.recurso",
            ),
        ),
        migrations.AddIndex(
            model_name="recurso",
            index=models.Index(
                fields=["filial", "ativo"], name="polpa_recur_filial__4471c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recurso",
            unique_together={("filial", "nome")},
        ),
    ]
