# Generated by Django 6.0.4 on 2026-08-25 17:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alerta_cliente_ajuste"),
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("polpa", "0005_planejamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="etapareceita",
            name="etapa",
            field=models.CharField(
                blank=True,
                help_text="A etapa do processo de polpa que esta corresponde.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApontamentoEtapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("recepcao", "Recepção da fruta"),
                            ("pesagem", "Pesagem"),
                            ("inspecao", "Inspeção"),
                            ("selecao", "Seleção"),
                            ("lavagem", "Lavagem"),
                            ("sanitizacao", "Sanitização"),
                            ("descascamento", "Descascamento"),
                            ("corte", "Corte"),
                            ("despolpamento", "Despolpamento"),
                            ("refino", "Peneiramento / refino"),
                            ("formulacao", "Formulação"),
                            ("homogeneizacao", "Homogeneização"),
                            ("envase", "Envase"),
                            ("selagem", "Selagem"),
                            ("identificacao", "Identificação do lote"),
                            ("congelamento", "Congelamento rápido"),
                            ("armazenamento", "Armazenamento em câmara fria"),
                            ("liberacao", "Liberação pelo controle de qualidade"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("sequencia", models.PositiveSmallIntegerField(default=0)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Não iniciada"),
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluída"),
                            ("pulada", "Não se aplica"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("iniciada_em", models.DateTimeField(blank=True, null=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "quantidade_entrada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantidade_saida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "motivo_perda",
                    models.CharField(
                        blank=True,
                        help_text="Casca e caroço, fruta descartada na seleção, sobra de linha…",
                        max_length=160,
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C medidos nesta etapa.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apontamentos",
                        to="polpa.recurso",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote de matéria-prima consumido ou de produto gerado aqui.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas_polpa",
                        to="estoque.loteproduto",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quem executou — a pergunta que a auditoria faz primeiro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas_processo",
                        to="polpa.ordempolpa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa apontada",
                "verbose_name_plural": "Etapas apontadas",
                "db_table": "polpa_apontamentos_etapa",
                "ordering": ["ordem", "sequencia", "id"],
                "indexes": [
                    models.Index(
                        fields=["filial", "situacao"],
                        name="polpa_apont_filial__af9250_idx",
                    ),
                    models.Index(
                        fields=["ordem", "sequencia"],
                        name="polpa_apont_ordem_i_66b2c9_idx",
                    ),
                ],
                "unique_together": {("ordem", "etapa")},
            },
        ),
    ]
