# Generated by Django 6.0.4 on 2026-08-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polpa", "0006_processo_produtivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamentoetapa",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("recepcao", "Recepção da matéria-prima"),
                    ("pesagem", "Pesagem"),
                    ("inspecao", "Inspeção"),
                    ("selecao", "Seleção"),
                    ("lavagem", "Lavagem"),
                    ("higienizacao", "Higienização"),
                    ("sanitizacao", "Sanitização"),
                    ("descascamento", "Descascamento"),
                    ("corte", "Corte"),
                    ("despolpamento", "Despolpamento"),
                    ("processamento", "Processamento"),
                    ("refino", "Peneiramento / refino"),
                    ("formulacao", "Formulação"),
                    ("mistura", "Mistura"),
                    ("homogeneizacao", "Homogeneização"),
                    ("pasteurizacao", "Pasteurização"),
                    ("resfriamento", "Resfriamento"),
                    ("envase", "Envase"),
                    ("selagem", "Selagem"),
                    ("identificacao", "Identificação do lote"),
                    ("congelamento", "Congelamento rápido"),
                    ("armazenamento", "Armazenamento em câmara fria"),
                    ("liberacao", "Liberação pelo controle de qualidade"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
