# Generated by Django 6.0.4 on 2026-08-25 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polpa", "0007_fluxo_por_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamentoetapa",
            name="volume_entrada",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Litros que entraram.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="apontamentoetapa",
            name="volume_saida",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Litros que saíram.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="apontamentoetapa",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("recepcao", "Recepção da matéria-prima"),
                    ("pesagem", "Pesagem"),
                    ("inspecao", "Inspeção"),
                    ("pesagem_ingredientes", "Pesagem dos ingredientes"),
                    ("selecao", "Seleção"),
                    ("lavagem", "Lavagem"),
                    ("higienizacao", "Higienização"),
                    ("sanitizacao", "Sanitização"),
                    ("descascamento", "Descascamento"),
                    ("corte", "Corte"),
                    ("despolpamento", "Despolpamento"),
                    ("processamento", "Processamento"),
                    ("refino", "Peneiramento / refino"),
                    ("formulacao", "Formulação"),
                    ("preparo_calda", "Preparação da calda/base"),
                    ("mistura", "Mistura"),
                    ("pasteurizacao", "Pasteurização"),
                    ("homogeneizacao", "Homogeneização"),
                    ("maturacao", "Maturação"),
                    ("saborizacao", "Adição de saborizantes"),
                    ("incorporacao_ar", "Incorporação de ar (overrun)"),
                    ("inclusoes", "Adição de inclusões"),
                    ("resfriamento", "Resfriamento"),
                    ("envase", "Envase"),
                    ("endurecimento", "Endurecimento"),
                    ("selagem", "Selagem"),
                    ("identificacao", "Identificação do lote"),
                    ("congelamento", "Congelamento rápido"),
                    ("armazenamento", "Armazenamento em câmara fria"),
                    ("liberacao", "Liberação pelo controle de qualidade"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
