# Generated by Django 6.0.4 on 2026-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polpa", "0008_sorvete_overrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamentoetapa",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("recepcao", "Recepção da matéria-prima"),
                    ("pesagem", "Pesagem"),
                    ("inspecao", "Inspeção"),
                    ("pesagem_ingredientes", "Pesagem dos ingredientes"),
                    ("selecao", "Seleção"),
                    ("lavagem", "Lavagem"),
                    ("higienizacao", "Higienização"),
                    ("sanitizacao", "Sanitização"),
                    ("descascamento", "Descascamento"),
                    ("corte", "Corte"),
                    ("despolpamento", "Despolpamento"),
                    ("processamento", "Processamento"),
                    ("refino", "Peneiramento / refino"),
                    ("formulacao", "Formulação"),
                    ("preparo_calda", "Preparação da calda/base"),
                    ("mistura", "Mistura"),
                    ("pasteurizacao", "Pasteurização"),
                    ("homogeneizacao", "Homogeneização"),
                    ("maturacao", "Maturação"),
                    ("saborizacao", "Adição de saborizantes"),
                    ("incorporacao_ar", "Incorporação de ar (overrun)"),
                    ("inclusoes", "Adição de inclusões"),
                    ("resfriamento", "Resfriamento"),
                    ("envase", "Envase"),
                    ("insercao_palito", "Inserção do palito"),
                    ("endurecimento", "Endurecimento"),
                    ("selagem", "Selagem"),
                    ("identificacao", "Identificação do lote"),
                    ("congelamento", "Congelamento rápido"),
                    ("desenforme", "Desenforme"),
                    ("embalagem", "Embalagem"),
                    ("empacotamento", "Empacotamento"),
                    ("armazenamento", "Armazenamento em câmara fria"),
                    ("liberacao", "Liberação pelo controle de qualidade"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
