# Generated by Django 5.2.17 on 2026-08-25 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alerta_cliente_ajuste"),
        ("polpa", "0009_picole"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordempolpa",
            name="insumos_reservados_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="ReservaInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("consumida", "Consumida"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="ativa",
                        max_length=12,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="polpa.ordempolpa",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_polpa",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo reservado",
                "verbose_name_plural": "Insumos reservados",
                "db_table": "polpa_reservas_insumo",
                "ordering": ["ordem", "produto"],
                "indexes": [
                    models.Index(
                        fields=["filial", "status"],
                        name="polpa_reser_filial__f55ebc_idx",
                    ),
                    models.Index(
                        fields=["ordem", "status"],
                        name="polpa_reser_ordem_i_045c34_idx",
                    ),
                ],
            },
        ),
    ]
