# Generated by Django 5.2.17 on 2026-08-25 20:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polpa", "0010_reserva_de_insumo"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="desvio_tolerado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5"),
                help_text="Quantos pontos percentuais abaixo do esperado ainda são normais. Esperado 60% com tolerância 5 alerta abaixo de 55%.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
