# Generated by Django 5.2.17 on 2026-08-25 20:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alerta_rendimento_polpa"),
        ("polpa", "0011_limite_de_rendimento"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustoReceita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nome",
                    models.CharField(help_text="Ex.: Energia do túnel", max_length=60),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("batida", "Por batida"),
                            ("kg", "Por quilo produzido"),
                            ("unidade", "Por unidade produzida"),
                        ],
                        default="batida",
                        max_length=10,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=160)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos_extras",
                        to="polpa.receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custo adicional da receita",
                "verbose_name_plural": "Custos adicionais da receita",
                "db_table": "polpa_custos_receita",
                "ordering": ["receita", "nome"],
                "indexes": [
                    models.Index(
                        fields=["filial", "ativo"],
                        name="polpa_custo_filial__3bc172_idx",
                    )
                ],
                "unique_together": {("receita", "nome")},
            },
        ),
    ]
