# Generated by Django 5.2.17 on 2026-08-25 20:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alerta_rendimento_polpa"),
        ("polpa", "0012_custo_configuravel"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subproduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("casca", "Casca"),
                            ("semente", "Semente / caroço"),
                            ("bagaco", "Bagaço"),
                            ("fora_padrao", "Fruta fora do padrão"),
                            ("residuo", "Resíduo de processamento"),
                            ("outro", "Outro"),
                        ],
                        db_index=True,
                        max_length=14,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text='Quando "outro", ou para detalhar: "casca com polpa aderida".',
                        max_length=120,
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("unidade", models.CharField(default="kg", max_length=6)),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("reaproveitamento", "Reaproveitamento"),
                            ("venda", "Venda"),
                            ("uso_interno", "Uso interno"),
                            ("doacao", "Doação"),
                            ("descarte", "Descarte"),
                        ],
                        db_index=True,
                        max_length=18,
                    ),
                ),
                ("destinatario", models.CharField(blank=True, max_length=120)),
                (
                    "valor_recebido",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="O que entrou pela venda deste subproduto.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "custo_destinacao",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="O que se pagou para dar fim a ele — coleta, aterro, frete.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "estoque_creditado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("data", models.DateField()),
                ("observacao", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subprodutos_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etapa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subprodutos",
                        to="polpa.apontamentoetapa",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprodutos",
                        to="polpa.ordempolpa",
                    ),
                ),
                (
                    "produto_estoque",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cadastre para que o reaproveitamento entre no estoque.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subprodutos_polpa",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subproduto ou resíduo",
                "verbose_name_plural": "Subprodutos e resíduos",
                "db_table": "polpa_subprodutos",
                "ordering": ["-data", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["filial", "destino"],
                        name="polpa_subpr_filial__04ec1e_idx",
                    ),
                    models.Index(
                        fields=["ordem"], name="polpa_subpr_ordem_i_fd45e9_idx"
                    ),
                    models.Index(
                        fields=["tipo", "destino"], name="polpa_subpr_tipo_0762c5_idx"
                    ),
                ],
            },
        ),
    ]
