# Generated by Django 6.0.4 on 2026-08-25 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alerta_rendimento_polpa"),
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("polpa", "0013_subprodutos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(db_index=True, max_length=60)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("congelados", "Congelados"),
                            ("resfriados", "Resfriados"),
                            ("antecamara", "Antecâmara / expedição"),
                            ("tunel", "Túnel de congelamento"),
                        ],
                        default="congelados",
                        max_length=15,
                    ),
                ),
                (
                    "temperatura_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C que a câmara mantém, no mínimo.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "temperatura_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="°C que a câmara mantém, no máximo.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "capacidade_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text='Quanto cabe. Nulo é "ninguém mediu", não "não cabe nada".',
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Câmara fria",
                "verbose_name_plural": "Câmaras frias",
                "db_table": "polpa_camaras",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="LoteArmazenado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endereco",
                    models.CharField(
                        blank=True,
                        help_text="Rua, bloco, prateleira — como a câmara é organizada.",
                        max_length=40,
                    ),
                ),
                (
                    "temperatura_entrada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("armazenado_em", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "camara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="polpa.camara",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armazenamento_polpa",
                        to="estoque.loteproduto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote armazenado",
                "verbose_name_plural": "Lotes armazenados",
                "db_table": "polpa_lotes_armazenados",
                "ordering": ["camara__nome", "endereco"],
            },
        ),
        migrations.AddIndex(
            model_name="camara",
            index=models.Index(
                fields=["filial", "ativo"], name="polpa_camar_filial__592526_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="camara",
            unique_together={("filial", "nome")},
        ),
        migrations.AddIndex(
            model_name="lotearmazenado",
            index=models.Index(
                fields=["filial", "camara"], name="polpa_lotes_filial__34cff4_idx"
            ),
        ),
    ]
