# Generated by Django 6.0.4 on 2026-08-25 22:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alerta_rendimento_polpa"),
        ("polpa", "0014_camara_fria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotearmazenado",
            name="endereco",
            field=models.CharField(
                blank=True,
                help_text="Endereço escrito à mão, para câmara ainda não mapeada.",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="Posicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("corredor", models.CharField(blank=True, max_length=20)),
                ("rua", models.CharField(blank=True, max_length=20)),
                ("prateleira", models.CharField(blank=True, max_length=20)),
                ("posicao", models.CharField(blank=True, max_length=20)),
                (
                    "capacidade_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text='Quanto cabe aqui. Nulo é "ninguém mediu".',
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "camara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posicoes",
                        to="polpa.camara",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posição",
                "verbose_name_plural": "Posições",
                "db_table": "polpa_posicoes",
                "ordering": [
                    "camara__nome",
                    "corredor",
                    "rua",
                    "prateleira",
                    "posicao",
                ],
            },
        ),
        migrations.AddField(
            model_name="lotearmazenado",
            name="posicao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lotes",
                to="polpa.posicao",
            ),
        ),
        migrations.CreateModel(
            name="LeituraTemperatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("temperatura", models.DecimalField(decimal_places=2, max_digits=6)),
                ("medida_em", models.DateTimeField(db_index=True)),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "camara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="polpa.camara",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "medido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leituras_polpa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura de temperatura",
                "verbose_name_plural": "Leituras de temperatura",
                "db_table": "polpa_leituras_temperatura",
                "ordering": ["-medida_em"],
                "indexes": [
                    models.Index(
                        fields=["filial", "camara", "-medida_em"],
                        name="polpa_leitu_filial__d66cdd_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="posicao",
            index=models.Index(
                fields=["filial", "camara", "ativo"],
                name="polpa_posic_filial__887140_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="posicao",
            unique_together={("camara", "corredor", "rua", "prateleira", "posicao")},
        ),
    ]
