# Generated by Django 6.0.4 on 2026-08-25 23:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alerta_rendimento_polpa"),
        ("polpa", "0015_posicao_e_temperatura"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Vazio = meta padrão, que vale todo dia sem meta própria.",
                        null=True,
                    ),
                ),
                (
                    "meta_kg",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quilos de produto acabado esperados no dia.",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta de produção",
                "verbose_name_plural": "Metas de produção",
                "db_table": "polpa_metas_producao",
                "ordering": ["-data"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("data__isnull", False)),
                        fields=("filial", "data"),
                        name="polpa_meta_por_dia",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("data__isnull", True)),
                        fields=("filial",),
                        name="polpa_meta_padrao_unica",
                    ),
                ],
            },
        ),
    ]
