# Generated by Django 5.2.17 on 2026-08-25 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_remove_constraints_indexes'),
        ('core', '0052_alerta_rendimento_polpa'),
        ('polpa', '0016_meta_producao'),
        ('produtos', '0031_produto_tempo_preparo_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_polpa', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_polpa', to='compras.pedidocompra')),
            ],
            options={
                'verbose_name': 'Requisição de insumo',
                'verbose_name_plural': 'Requisições de insumo',
                'db_table': 'polpa_requisicoes_insumo',
                'ordering': ['-numero'],
                'unique_together': {('filial', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=160)),
                ('codigo', models.CharField(blank=True, max_length=40)),
                ('unidade', models.CharField(blank=True, max_length=6)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('necessario', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('disponivel', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=160)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao_polpa', to='produtos.produto')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='polpa.requisicaoinsumo')),
            ],
            options={
                'verbose_name': 'Item da requisição',
                'verbose_name_plural': 'Itens da requisição',
                'db_table': 'polpa_requisicoes_insumo_itens',
                'ordering': ['descricao'],
            },
        ),
    ]
