# Generated by Django 5.2.17 on 2026-08-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alerta_rendimento_polpa"),
        ("polpa", "0017_requisicao_de_insumo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text='Sem espaço nem acento: "fermentacao", "defumacao".',
                        max_length=20,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text='Como aparece na tela: "Fermentação".', max_length=60
                    ),
                ),
                (
                    "sequencia",
                    models.PositiveSmallIntegerField(
                        default=99,
                        help_text="Posição na sequência. As etapas do vocabulário vão de 0 a 33.",
                    ),
                ),
                (
                    "exige_peso",
                    models.BooleanField(
                        default=True,
                        help_text="Pede entrada e saída — é o que alimenta perda e rendimento.",
                    ),
                ),
                ("exige_temperatura", models.BooleanField(default=False)),
                ("instrucao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de processo",
                "verbose_name_plural": "Etapas de processo",
                "db_table": "polpa_etapas_processo",
                "ordering": ["sequencia", "nome"],
                "indexes": [
                    models.Index(
                        fields=["filial", "ativo"],
                        name="polpa_etapa_filial__8194eb_idx",
                    )
                ],
                "unique_together": {("filial", "codigo")},
            },
        ),
    ]
