"""
A ordenacao da leitura ganha desempate por `-pk`.

So' mexe em `Meta.options`: e' mudanca de ESTADO, sem SQL nenhum. Nenhuma
linha e' tocada e a migration roda em tempo constante -- o que importa porque
ela roda como release command, e migration demorada em tabela grande derruba
o container.
"""
# Generated by Django 5.2.17 on 2026-08-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polpa", "0018_etapa_configuravel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leituratemperatura",
            options={
                "ordering": ["-medida_em", "-pk"],
                "verbose_name": "Leitura de temperatura",
                "verbose_name_plural": "Leituras de temperatura",
            },
        ),
    ]
