# Generated by Django 5.2.17 on 2026-08-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_usuario_menu_favoritos"),
        ("polpa", "0019_desempate_da_leitura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichaproduto",
            name="tipo",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name="TipoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador gravado na ficha. Não muda depois de criado.",
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                (
                    "classe",
                    models.CharField(
                        help_text="Decide o que a ficha pergunta e como a produção trata o item.",
                        max_length=20,
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("sistema", models.BooleanField(db_index=True, default=False)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de item",
                "verbose_name_plural": "Tipos de item",
                "db_table": "polpa_tipos_item",
                "ordering": ["classe", "nome"],
                "indexes": [
                    models.Index(
                        fields=["filial", "classe", "ativo"],
                        name="polpa_tipos_filial__8678a5_idx",
                    )
                ],
                "unique_together": {("filial", "codigo")},
            },
        ),
    ]
