# Generated by Django 6.0.4 on 2026-08-26 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_food_service_so_padaria'),
        ('logistica', '0014_reconciliar_mdfe_2_autorizado'),
        ('polpa', '0019_desempate_da_leitura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaFria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperatura_bau', models.DecimalField(blank=True, decimal_places=2, help_text='°C medidos dentro do baú, na hora de fechar a porta.', max_digits=6, null=True)),
                ('medida_em', models.DateTimeField(blank=True, null=True)),
                ('saida_em', models.DateTimeField(blank=True, help_text='Quando o caminhão saiu de fato.', null=True)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('medido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_medidas_polpa', to=settings.AUTH_USER_MODEL)),
                ('romaneio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_polpa', to='logistica.romaneiocarga')),
            ],
            options={
                'verbose_name': 'Carga fria',
                'verbose_name_plural': 'Cargas frias',
                'db_table': 'polpa_cargas_frias',
                'ordering': ['-saida_em', '-id'],
            },
        ),
    ]
