# Generated by Django 6.0.4 on 2026-08-26 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_food_service_so_padaria'),
        ('logistica', '0014_reconciliar_mdfe_2_autorizado'),
        ('polpa', '0020_carga_fria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaFria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('recebido_por', models.CharField(blank=True, help_text='Nome de quem recebeu — é ele que responde pelo estado do produto.', max_length=120)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, help_text='°C medidos na entrega, antes de o produto sair do baú.', max_digits=6, null=True)),
                ('ocorrencia', models.CharField(blank=True, choices=[('recusa', 'Recusada pelo cliente'), ('temperatura', 'Recusada por temperatura'), ('avaria', 'Produto avariado'), ('ausente', 'Ninguém para receber'), ('endereco', 'Endereço não encontrado'), ('outra', 'Outra')], help_text='Preenchido quando a parada não foi entregue.', max_length=15)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_polpa', to='logistica.itemromaneiocarga')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_polpa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'polpa_entregas_frias',
                'ordering': ['-entregue_em', '-id'],
            },
        ),
    ]
