# Generated by Django 6.0.4 on 2026-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polpa", "0021_entrega_fria"),
    ]

    operations = [
        migrations.AddField(
            model_name="recebimento",
            name="quantidade_caixas",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantas caixas vieram nesta carga — o que se deve devolver ao produtor.",
                null=True,
            ),
        ),
    ]
