# Generated by Django 6.0.4 on 2026-08-18 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0014_vincular_rota_motorista_veiculo"),
        ("core", "0046_permissao_modulo_moda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        blank=True,
                        help_text="Deixe vazio para categoria raiz; preencha para subcategoria.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategorias",
                        to="moda.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "moda_categorias",
                "ordering": ["nome"],
                "abstract": False,
                "unique_together": {("filial", "pai", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Colecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                ("ano", models.PositiveIntegerField(blank=True, null=True)),
                ("estacao", models.CharField(blank=True, max_length=40)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coleção",
                "verbose_name_plural": "Coleções",
                "db_table": "moda_colecoes",
                "ordering": ["-ano", "nome"],
                "abstract": False,
                "unique_together": {("filial", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Cor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "sigla",
                    models.CharField(
                        help_text="Abreviação usada no SKU (ex.: AMA para Amarelo).",
                        max_length=6,
                    ),
                ),
                (
                    "hex_cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor em hexadecimal (#RRGGBB), para exibição.",
                        max_length=7,
                    ),
                ),
                ("codigo_pantone", models.CharField(blank=True, max_length=30)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cor",
                "verbose_name_plural": "Cores",
                "db_table": "moda_cores",
                "ordering": ["nome"],
                "abstract": False,
                "unique_together": {("filial", "nome"), ("filial", "sigla")},
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=60)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("adulto", "Adulto"),
                            ("plus_size", "Plus Size"),
                            ("infantil", "Infantil"),
                            ("unico", "Único"),
                            ("outro", "Outro"),
                        ],
                        default="adulto",
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=160)),
                (
                    "padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Grade padrão do sistema (Adulto, Plus Size, Infantil).",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "db_table": "moda_grades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Linha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha",
                "verbose_name_plural": "Linhas",
                "db_table": "moda_linhas",
                "ordering": ["nome"],
                "abstract": False,
                "unique_together": {("filial", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
                "db_table": "moda_marcas",
                "ordering": ["nome"],
                "abstract": False,
                "unique_together": {("filial", "nome")},
            },
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "gola",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("careca", "Careca"),
                            ("polo", "Polo"),
                            ("v", "V"),
                            ("frade", "Frade"),
                            ("redonda", "Redonda"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "manga",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sem_manga", "Sem manga"),
                            ("curta", "Curta"),
                            ("longa", "Longa"),
                            ("com_punho", "Com punho"),
                            ("raglan", "Raglan"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
                "db_table": "moda_modelos",
                "ordering": ["nome"],
                "abstract": False,
                "unique_together": {("filial", "nome")},
            },
        ),
        migrations.CreateModel(
            name="ProdutoModa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código interno. Vira o prefixo do SKU das variantes.",
                        max_length=30,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Referência comercial/do cliente, quando difere do código.",
                        max_length=40,
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("ativo", "Ativo"),
                            ("descontinuado", "Descontinuado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="moda/produtos/fotos/"
                    ),
                ),
                (
                    "desenho_tecnico",
                    models.FileField(
                        blank=True,
                        help_text="Desenho técnico da peça (imagem ou PDF).",
                        null=True,
                        upload_to="moda/produtos/desenhos/",
                    ),
                ),
                (
                    "ficha_tecnica",
                    models.FileField(
                        blank=True,
                        help_text="Ficha técnica em arquivo. A ficha estruturada vem no módulo Engenharia.",
                        null=True,
                        upload_to="moda/produtos/fichas/",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoria raiz ou subcategoria — as duas vivem no mesmo cadastro.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.categoria",
                    ),
                ),
                (
                    "colecao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.colecao",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="Define quais tamanhos viram variante.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.grade",
                    ),
                ),
                (
                    "linha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.linha",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.marca",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Modelagem base — é dela que vêm gola e manga.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto de moda",
                "verbose_name_plural": "Produtos de moda",
                "db_table": "moda_produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ProdutoCor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia_cor", models.CharField(blank=True, max_length=40)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="moda/produtos/cores/"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "cor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="moda.cor",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cores",
                        to="moda.produtomoda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cor do produto",
                "verbose_name_plural": "Cores do produto",
                "db_table": "moda_produto_cores",
                "ordering": ["cor__nome"],
                "unique_together": {("produto", "cor")},
            },
        ),
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "sigla",
                    models.CharField(
                        help_text="Como aparece na grade e no SKU (PP, M, G1, 12).",
                        max_length=6,
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=40)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("adulto", "Adulto"),
                            ("plus_size", "Plus Size"),
                            ("infantil", "Infantil"),
                            ("unico", "Único"),
                            ("outro", "Outro"),
                        ],
                        default="adulto",
                        max_length=20,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho",
                "verbose_name_plural": "Tamanhos",
                "db_table": "moda_tamanhos",
                "ordering": ["tipo", "ordem", "sigla"],
                "unique_together": {("filial", "sigla")},
            },
        ),
        migrations.CreateModel(
            name="ItemGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="moda.grade",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_grade",
                        to="moda.tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho da grade",
                "verbose_name_plural": "Tamanhos da grade",
                "db_table": "moda_itens_grade",
                "ordering": ["ordem", "id"],
                "unique_together": {("grade", "tamanho")},
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="tamanhos",
            field=models.ManyToManyField(
                related_name="grades", through="moda.ItemGrade", to="moda.tamanho"
            ),
        ),
        migrations.CreateModel(
            name="Tecido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "composicao",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 100% Poliéster; 67% Poliéster 33% Algodão.",
                        max_length=120,
                    ),
                ),
                (
                    "gramatura",
                    models.PositiveIntegerField(
                        blank=True, help_text="Em g/m².", null=True
                    ),
                ),
                (
                    "largura_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Largura útil do rolo, usada no cálculo de encaixe.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tecidos_moda",
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tecido",
                "verbose_name_plural": "Tecidos",
                "db_table": "moda_tecidos",
                "ordering": ["nome"],
                "abstract": False,
                "unique_together": {("filial", "nome")},
            },
        ),
        migrations.AddField(
            model_name="produtomoda",
            name="tecido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produtos",
                to="moda.tecido",
            ),
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=60)),
                ("codigo_barras", models.CharField(blank=True, max_length=60)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="moda.produtomoda",
                    ),
                ),
                (
                    "produto_cor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="moda.produtocor",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variantes",
                        to="moda.tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante",
                "verbose_name_plural": "Variantes",
                "db_table": "moda_variantes",
                "ordering": [
                    "produto_cor__cor__nome",
                    "tamanho__ordem",
                    "tamanho__sigla",
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("filial", "nome")},
        ),
        migrations.AddIndex(
            model_name="produtomoda",
            index=models.Index(
                fields=["filial", "status"], name="moda_produt_filial__87c325_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produtomoda",
            index=models.Index(
                fields=["filial", "nome"], name="moda_produt_filial__ffc84c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="produtomoda",
            unique_together={("filial", "codigo")},
        ),
        migrations.AddIndex(
            model_name="variante",
            index=models.Index(fields=["sku"], name="moda_varian_sku_2c3064_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="variante",
            unique_together={("produto", "produto_cor", "tamanho"), ("produto", "sku")},
        ),
    ]
