# Generated by Django 6.0.4 on 2026-08-18 01:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_vincular_rota_motorista_veiculo"),
        ("core", "0046_permissao_modulo_moda"),
        ("moda", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                ("contato_nome", models.CharField(blank=True, max_length=120)),
                ("contato_telefone", models.CharField(blank=True, max_length=30)),
                (
                    "data_pedido",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "data_prevista_entrega",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="A data que o cliente combinou — é dela que sai a priorização do PCP.",
                        null=True,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("orcamento", "Orçamento"),
                            ("confirmado", "Pedido Confirmado"),
                            ("aguardando_arte", "Aguardando Arte"),
                            ("aguardando_material", "Aguardando Material"),
                            ("liberado_producao", "Liberado para Produção"),
                            ("em_producao", "Em Produção"),
                            ("em_acabamento", "Em Acabamento"),
                            ("pronto", "Pronto"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="orcamento",
                        max_length=25,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_moda",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de produção",
                "verbose_name_plural": "Pedidos de produção",
                "db_table": "moda_pedidos",
                "ordering": ["-data_pedido", "-numero"],
                "indexes": [
                    models.Index(
                        fields=["filial", "status"],
                        name="moda_pedido_filial__2a72bb_idx",
                    ),
                    models.Index(
                        fields=["filial", "data_prevista_entrega"],
                        name="moda_pedido_filial__18f227_idx",
                    ),
                ],
                "unique_together": {("filial", "numero")},
            },
        ),
    ]
