# Generated by Django 6.0.4 on 2026-08-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0002_pedido_producao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPedidoProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Conjunto — Camisa + Calção. Usado quando não há produto de catálogo.",
                        max_length=160,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=40)),
                (
                    "gola",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("careca", "Careca"),
                            ("polo", "Polo"),
                            ("v", "V"),
                            ("frade", "Frade"),
                            ("redonda", "Redonda"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "manga",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sem_manga", "Sem manga"),
                            ("curta", "Curta"),
                            ("longa", "Longa"),
                            ("com_punho", "Com punho"),
                            ("raglan", "Raglan"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "acabamento",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: barra dobrada, punho em ribana, escudo em patch aplicado.",
                        max_length=120,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, help_text="Posição do item na ficha."
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="moda.cor",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="moda.modelo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="moda.pedidoproducao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        help_text='Do catálogo. Deixe vazio e descreva em "Descrição" se ainda não houver cadastro.',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="moda.produtomoda",
                    ),
                ),
                (
                    "tecido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="moda.tecido",
                        verbose_name="Tecido / Malha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do pedido",
                "verbose_name_plural": "Itens do pedido",
                "db_table": "moda_itens_pedido",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
