# Generated by Django 6.0.4 on 2026-08-18 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0003_item_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personalizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("arte", "Arte / estampa"),
                            ("escudo", "Escudo / logo"),
                            ("nome", "Nome"),
                            ("numero", "Número"),
                            ("patrocinio", "Patrocínio"),
                            ("outro", "Outro"),
                        ],
                        default="arte",
                        max_length=20,
                        verbose_name="Tipo de impressão",
                    ),
                ),
                (
                    "tecnica",
                    models.CharField(
                        choices=[
                            ("sublimacao", "Sublimação"),
                            ("silk", "Silk"),
                            ("bordado", "Bordado"),
                            ("dtf", "DTF"),
                            ("dtg", "DTG"),
                            ("transfer", "Transfer"),
                            ("patch", "Patch"),
                            ("sem_impressao", "Sem impressão"),
                            ("outro", "Outro"),
                        ],
                        default="sublimacao",
                        max_length=20,
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: peito esquerdo, costas, manga direita.",
                        max_length=80,
                    ),
                ),
                (
                    "nome_personalizado",
                    models.CharField(
                        blank=True,
                        help_text="Nome que vai na peça, quando houver.",
                        max_length=80,
                    ),
                ),
                (
                    "numero_personalizado",
                    models.CharField(
                        blank=True,
                        help_text="Número que vai na peça (ex.: 25).",
                        max_length=10,
                    ),
                ),
                (
                    "patrocinios",
                    models.TextField(
                        blank=True, help_text="Quais marcas e onde entram."
                    ),
                ),
                ("quantidade_patrocinadores", models.PositiveIntegerField(default=0)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        help_text="PNG, JPG, PDF, CDR, SVG ou AI.",
                        null=True,
                        upload_to="moda/artes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "pdf",
                                    "cdr",
                                    "svg",
                                    "ai",
                                ]
                            )
                        ],
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personalizacoes",
                        to="moda.itempedidoproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personalização",
                "verbose_name_plural": "Personalizações",
                "db_table": "moda_personalizacoes",
                "ordering": ["id"],
            },
        ),
    ]
