# Generated by Django 6.0.4 on 2026-08-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_permissao_modulo_moda"),
        ("moda", "0004_personalizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockupVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                (
                    "posicao",
                    models.CharField(
                        choices=[
                            ("frente_camisa", "Frente da camisa"),
                            ("costas_camisa", "Costas da camisa"),
                            ("frente_calcao", "Frente do calção"),
                            ("costas_calcao", "Costas do calção"),
                        ],
                        max_length=20,
                    ),
                ),
                ("imagem", models.ImageField(upload_to="moda/mockups/")),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mockup visual",
                "verbose_name_plural": "Mockups visuais",
                "db_table": "moda_mockups",
                "ordering": ["posicao", "nome"],
                "unique_together": {("filial", "nome", "posicao")},
            },
        ),
        migrations.CreateModel(
            name="VisualItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posicao",
                    models.CharField(
                        choices=[
                            ("frente_camisa", "Frente da camisa"),
                            ("costas_camisa", "Costas da camisa"),
                            ("frente_calcao", "Frente do calção"),
                            ("costas_calcao", "Costas do calção"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Arte específica deste pedido.",
                        null=True,
                        upload_to="moda/visuais/",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=80)),
                ("numero", models.CharField(blank=True, max_length=10)),
                ("observacoes", models.CharField(blank=True, max_length=160)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visuais",
                        to="moda.itempedidoproducao",
                    ),
                ),
                (
                    "mockup",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ou escolha uma imagem já cadastrada.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usos",
                        to="moda.mockupvisual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual do item",
                "verbose_name_plural": "Visuais do item",
                "db_table": "moda_visuais_item",
                "ordering": ["posicao"],
                "unique_together": {("item", "posicao")},
            },
        ),
    ]
