# Generated by Django 6.0.4 on 2026-08-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0005_visual_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemGradePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="moda.itempedidoproducao",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades_pedido",
                        to="moda.tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho do item",
                "verbose_name_plural": "Grade do item",
                "db_table": "moda_grade_pedido",
                "ordering": ["tamanho__ordem", "tamanho__sigla"],
                "unique_together": {("item", "tamanho")},
            },
        ),
    ]
