# Generated by Django 6.0.4 on 2026-08-18 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0006_grade_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalizacaoIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=80)),
                ("numero", models.CharField(blank=True, max_length=10)),
                ("observacoes", models.CharField(blank=True, max_length=160)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individuais",
                        to="moda.itempedidoproducao",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="individuais",
                        to="moda.pedidoproducao",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="individuais",
                        to="moda.tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personalização individual",
                "verbose_name_plural": "Personalizações individuais",
                "db_table": "moda_personalizacao_individual",
                "ordering": ["ordem", "id"],
                "indexes": [
                    models.Index(
                        fields=["pedido", "item", "tamanho"],
                        name="moda_person_pedido__2eb60c_idx",
                    )
                ],
            },
        ),
    ]
