# Generated by Django 6.0.4 on 2026-08-18 14:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0015_logintegracaofiscal_usuario"),
        ("moda", "0007_personalizacao_individual"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedidoproducao",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                verbose_name="Valor unitário",
            ),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="acrescimo",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="condicao_pagamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Define em quantas parcelas o saldo é dividido e de quanto em quanto tempo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_moda",
                to="financeiro.condicaopagamento",
            ),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="entrada",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Sinal combinado. Vira a primeira conta a receber, com vencimento na data do pedido.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="financeiro_gerado_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="forma_pagamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_moda",
                to="financeiro.formapagamento",
            ),
        ),
        migrations.AddField(
            model_name="pedidoproducao",
            name="frete",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
