# Generated by Django 6.0.4 on 2026-08-18 15:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0008_valores_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "versao",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Suba a versão quando mudar consumo ou material — o custo muda junto.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("aprovada", "Aprovada"),
                            ("obsoleta", "Obsoleta"),
                        ],
                        db_index=True,
                        default="rascunho",
                        max_length=15,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Especificação técnica: modelagem, costura, acabamentos, tolerâncias.",
                    ),
                ),
                (
                    "desenho_tecnico",
                    models.FileField(
                        blank=True,
                        help_text="PNG, JPG, PDF, CDR ou AI. Em branco, usa o desenho do produto.",
                        null=True,
                        upload_to="moda/fichas/desenhos/",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha",
                        to="moda.produtomoda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha técnica",
                "verbose_name_plural": "Fichas técnicas",
                "db_table": "moda_fichas_tecnicas",
                "ordering": ["produto__codigo"],
            },
        ),
        migrations.CreateModel(
            name="ImagemFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="moda/fichas/imagens/")),
                ("legenda", models.CharField(blank=True, max_length=120)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="moda.fichatecnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da ficha",
                "verbose_name_plural": "Imagens da ficha",
                "db_table": "moda_fichas_imagens",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecido_principal", "Tecido principal"),
                            ("forro", "Forro"),
                            ("linha", "Linha"),
                            ("elastico", "Elástico"),
                            ("ziper", "Zíper"),
                            ("botao", "Botão"),
                            ("etiqueta", "Etiqueta"),
                            ("tag", "Tag"),
                            ("embalagem", "Embalagem"),
                            ("aviamento", "Aviamentos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="Ex.: Malha Dry Fit 100% poliéster 140g, Zíper nylon nº 5 destacável.",
                        max_length=140,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código do material no estoque ou no fornecedor.",
                        max_length=40,
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("m", "m"),
                            ("m2", "m²"),
                            ("cm", "cm"),
                            ("kg", "kg"),
                            ("g", "g"),
                            ("un", "un"),
                            ("par", "par"),
                            ("pc", "pç"),
                            ("rolo", "rolo"),
                            ("cone", "cone"),
                        ],
                        default="un",
                        max_length=6,
                    ),
                ),
                (
                    "consumo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Quanto entra em UMA peça, na unidade escolhida.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "perda",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Percentual de perda no corte/costura. Ex.: 8 para 8%.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "custo_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Preço de UMA unidade do material.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=160)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiais",
                        to="moda.fichatecnica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material da ficha",
                "verbose_name_plural": "Materiais da ficha",
                "db_table": "moda_fichas_materiais",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="fichatecnica",
            index=models.Index(
                fields=["filial", "status"], name="moda_fichas_filial__29300c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialficha",
            index=models.Index(
                fields=["ficha", "tipo"], name="moda_fichas_ficha_i_4556a4_idx"
            ),
        ),
    ]
