# Generated by Django 6.0.4 on 2026-08-18 15:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0009_ficha_tecnica"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=80)),
                ("observacao", models.TextField(blank=True)),
                (
                    "sequencia",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Posição no fluxo da fábrica. Serve de sugestão ao montar um roteiro.",
                    ),
                ),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("modelagem", "Modelagem"),
                            ("corte", "Corte"),
                            ("estamparia", "Estamparia"),
                            ("costura", "Costura"),
                            ("acabamento", "Acabamento"),
                            ("qualidade", "Qualidade"),
                            ("expedicao", "Expedição"),
                        ],
                        default="costura",
                        max_length=20,
                    ),
                ),
                (
                    "maquina",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Reta, Overloque, Galoneira, Calandra, Bordadeira.",
                        max_length=80,
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        help_text="Quem responde pela operação — pessoa ou equipe.",
                        max_length=80,
                    ),
                ),
                (
                    "tempo_padrao",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Minutos que UMA peça leva nesta operação.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Tempo padrão (min/peça)",
                    ),
                ),
                (
                    "tipo_custo",
                    models.CharField(
                        choices=[("hora", "Por hora"), ("peca", "Por peça")],
                        default="hora",
                        max_length=6,
                    ),
                ),
                (
                    "custo",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text='Valor na unidade escolhida em "Tipo de custo".',
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "capacidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Quanto o SETOR entrega por hora, somando máquinas e pessoas.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Capacidade (peças/hora)",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operação",
                "verbose_name_plural": "Operações",
                "db_table": "moda_operacoes",
                "ordering": ["sequencia", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Roteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("versao", models.PositiveSmallIntegerField(default=1)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roteiro",
                        to="moda.produtomoda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roteiro de produção",
                "verbose_name_plural": "Roteiros de produção",
                "db_table": "moda_roteiros",
                "ordering": ["produto__codigo"],
            },
        ),
        migrations.CreateModel(
            name="OperacaoRoteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequencia",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ordem desta etapa NESTE produto."
                    ),
                ),
                (
                    "tempo_padrao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Em branco, usa o tempo padrão da operação.",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Tempo (min/peça)",
                    ),
                ),
                (
                    "custo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Em branco, usa o custo da operação.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "capacidade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Em branco, usa a capacidade da operação.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Capacidade (peças/hora)",
                    ),
                ),
                ("maquina", models.CharField(blank=True, max_length=80)),
                ("responsavel", models.CharField(blank=True, max_length=80)),
                ("observacao", models.CharField(blank=True, max_length=160)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "operacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etapas",
                        to="moda.operacao",
                    ),
                ),
                (
                    "roteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="moda.roteiro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa do roteiro",
                "verbose_name_plural": "Etapas do roteiro",
                "db_table": "moda_roteiro_operacoes",
                "ordering": ["sequencia", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="operacao",
            index=models.Index(
                fields=["filial", "setor"], name="moda_operac_filial__f6fcf2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="operacao",
            unique_together={("filial", "nome")},
        ),
        migrations.AlterUniqueTogether(
            name="operacaoroteiro",
            unique_together={("roteiro", "operacao")},
        ),
    ]
