# Generated by Django 6.0.4 on 2026-08-18 15:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0010_roteiro_producao"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacidadeSetor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("modelagem", "Modelagem"),
                            ("corte", "Corte"),
                            ("estamparia", "Estamparia"),
                            ("costura", "Costura"),
                            ("acabamento", "Acabamento"),
                            ("qualidade", "Qualidade"),
                            ("expedicao", "Expedição"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "postos",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Quantas pessoas ou máquinas trabalham em paralelo neste setor.",
                    ),
                ),
                (
                    "horas_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                        verbose_name="Horas por dia",
                    ),
                ),
                (
                    "dias_semana",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Dias por semana",
                    ),
                ),
                (
                    "eficiencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("85"),
                        help_text="Percentual da jornada realmente produtivo. 85% é um ponto de partida comum.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Eficiência (%)",
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidade do setor",
                "verbose_name_plural": "Capacidade dos setores",
                "db_table": "moda_capacidade_setor",
                "ordering": ["setor"],
                "unique_together": {("filial", "setor")},
            },
        ),
    ]
