# Generated by Django 6.0.4 on 2026-08-18 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0011_capacidade_setor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(db_index=True, max_length=20)),
                ("ano", models.PositiveSmallIntegerField()),
                ("sequencial", models.PositiveIntegerField()),
                ("quantidade", models.PositiveIntegerField()),
                ("prazo", models.DateField(blank=True, null=True)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emitida", "Emitida"),
                            ("liberada", "Liberada"),
                            ("em_producao", "Em Produção"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="emitida",
                        max_length=15,
                    ),
                ),
                ("emitida_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "emitida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Uma OP por produto do pedido — é o que caminha pela fábrica.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="moda.itempedidoproducao",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="moda.pedidoproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de produção",
                "verbose_name_plural": "Ordens de produção",
                "db_table": "moda_ordens_producao",
                "ordering": ["-ano", "-sequencial"],
                "indexes": [
                    models.Index(
                        fields=["filial", "status"],
                        name="moda_ordens_filial__7ac17e_idx",
                    ),
                    models.Index(
                        fields=["filial", "prazo"],
                        name="moda_ordens_filial__90991e_idx",
                    ),
                ],
                "unique_together": {("filial", "ano", "sequencial")},
            },
        ),
    ]
