# Generated by Django 6.0.4 on 2026-08-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0012_ordem_producao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaOrdem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("pedido", "Pedido"),
                            ("planejamento", "Planejamento"),
                            ("materiais", "Materiais"),
                            ("corte", "Corte"),
                            ("estampa", "Sublimação / Bordado / Silk"),
                            ("costura", "Costura"),
                            ("acabamento", "Acabamento"),
                            ("qualidade", "Qualidade"),
                            ("embalagem", "Embalagem"),
                            ("expedicao", "Expedição"),
                            ("entrega", "Entrega"),
                        ],
                        max_length=15,
                    ),
                ),
                ("sequencia", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluída"),
                            ("pulada", "Não se aplica"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=15,
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True,
                        help_text="Quem responde por esta etapa.",
                        max_length=80,
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de início"
                    ),
                ),
                ("data_prevista", models.DateField(blank=True, null=True)),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data concluída"
                    ),
                ),
                (
                    "quantidade_planejada",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Em branco, herda o produzido da etapa anterior.",
                        null=True,
                    ),
                ),
                ("quantidade_produzida", models.PositiveIntegerField(default=0)),
                (
                    "perda",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Peças perdidas nesta etapa: refugo, corte errado, defeito.",
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapas_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="moda.ordemproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa da ordem",
                "verbose_name_plural": "Etapas da ordem",
                "db_table": "moda_etapas_ordem",
                "ordering": ["sequencia"],
                "indexes": [
                    models.Index(
                        fields=["ordem", "status"],
                        name="moda_etapas_ordem_i_b4f892_idx",
                    )
                ],
                "unique_together": {("ordem", "etapa")},
            },
        ),
    ]
