# Generated by Django 6.0.4 on 2026-08-18 19:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0013_fluxo_producao"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroCorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "lote",
                    models.CharField(
                        blank=True,
                        help_text="Lote do rolo de tecido. É por ele que se rastreia um defeito de matéria-prima.",
                        max_length=40,
                    ),
                ),
                ("data", models.DateField(blank=True, null=True)),
                ("responsavel", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("cortado", "Cortado"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="planejado",
                        max_length=12,
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=0, help_text="Peças cortadas neste enfesto."
                    ),
                ),
                (
                    "largura_tecido",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Largura do tecido (m)",
                    ),
                ),
                (
                    "comprimento_encaixe",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Comprimento do encaixe (m)",
                    ),
                ),
                (
                    "folhas",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Folhas do enfesto — quantas camadas de tecido foram sobrepostas.",
                    ),
                ),
                (
                    "aproveitamento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Vem do encaixe: quanto da área do tecido virou peça. Ex.: 87,5.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Aproveitamento (%)",
                    ),
                ),
                (
                    "consumo_planejado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Em branco, sai da ficha técnica: consumo do tecido principal × quantidade.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Consumo planejado (m)",
                    ),
                ),
                (
                    "consumo_real",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Metros de tecido efetivamente gastos.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Consumo real (m)",
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Em branco, usa a cor do item da ordem.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="moda.cor",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="moda.ordemproducao",
                    ),
                ),
                (
                    "tecido",
                    models.ForeignKey(
                        blank=True,
                        help_text="Em branco, usa o tecido do item da ordem.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="moda.tecido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de corte",
                "verbose_name_plural": "Registros de corte",
                "db_table": "moda_cortes",
                "ordering": ["-data", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemCorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="moda.tamanho",
                    ),
                ),
                (
                    "corte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade",
                        to="moda.registrocorte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho do corte",
                "verbose_name_plural": "Grade do corte",
                "db_table": "moda_cortes_grade",
                "ordering": ["tamanho__ordem", "tamanho__sigla"],
            },
        ),
        migrations.AddIndex(
            model_name="registrocorte",
            index=models.Index(
                fields=["filial", "status"], name="moda_cortes_filial__1e1f3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrocorte",
            index=models.Index(fields=["ordem"], name="moda_cortes_ordem_i_963211_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="registrocorte",
            unique_together={("filial", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="itemcorte",
            unique_together={("corte", "tamanho")},
        ),
    ]
