# Generated by Django 6.0.4 on 2026-08-18 19:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0014_controle_corte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Encaixe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex.: Camisa gola redonda — P ao GG, tecido 1,60 m.",
                        max_length=120,
                    ),
                ),
                (
                    "comprimento",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="O comprimento do risco, em metros.",
                        max_digits=8,
                        verbose_name="Comprimento do encaixe (m)",
                    ),
                ),
                (
                    "largura_tecido",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Largura útil do tecido, já descontada a ourela.",
                        max_digits=6,
                        verbose_name="Largura do tecido (m)",
                    ),
                ),
                (
                    "quantidade_pecas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantas peças cabem neste risco, somando todos os tamanhos.",
                        verbose_name="Quantidade de peças",
                    ),
                ),
                (
                    "area_util",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Soma da área dos moldes encaixados. Sai do CAD — é o que o sistema não consegue calcular sozinho.",
                        max_digits=10,
                        verbose_name="Área útil (m²)",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        help_text="O arquivo do risco: PLT, DXF, PDF ou imagem.",
                        null=True,
                        upload_to="moda/encaixes/",
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaixes",
                        to="moda.modelo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        help_text="O produto que este risco atende. Em branco para um encaixe genérico.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaixes",
                        to="moda.produtomoda",
                    ),
                ),
                (
                    "tecido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encaixes",
                        to="moda.tecido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaixe",
                "verbose_name_plural": "Encaixes",
                "db_table": "moda_encaixes",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="registrocorte",
            name="encaixe",
            field=models.ForeignKey(
                blank=True,
                help_text="Ligando o encaixe, o aproveitamento passa a ser calculado dele.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cortes",
                to="moda.encaixe",
            ),
        ),
        migrations.AddIndex(
            model_name="encaixe",
            index=models.Index(
                fields=["filial", "produto"], name="moda_encaix_filial__4a0f08_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="encaixe",
            unique_together={("filial", "nome")},
        ),
    ]
