# Generated by Django 6.0.4 on 2026-08-18 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0015_encaixe"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialficha",
            name="produto_estoque",
            field=models.ForeignKey(
                blank=True,
                help_text="Ligue para o sistema conferir saldo e permitir reserva. A unidade precisa ser a mesma — não há conversão.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materiais_moda",
                to="produtos.produto",
                verbose_name="Produto no estoque",
            ),
        ),
        migrations.CreateModel(
            name="RequisicaoMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("atendida", "Atendida"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="aberta",
                        max_length=12,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisicoes_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisição de material",
                "verbose_name_plural": "Requisições de material",
                "db_table": "moda_requisicoes_material",
                "ordering": ["-numero"],
                "unique_together": {("filial", "numero")},
            },
        ),
        migrations.CreateModel(
            name="ItemRequisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=160)),
                ("codigo", models.CharField(blank=True, max_length=40)),
                ("unidade", models.CharField(blank=True, max_length=6)),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=12)),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio quando o material da ficha ainda não foi ligado ao estoque.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_requisicao_moda",
                        to="produtos.produto",
                    ),
                ),
                (
                    "requisicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="moda.requisicaomaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da requisição",
                "verbose_name_plural": "Itens da requisição",
                "db_table": "moda_requisicoes_itens",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="ReservaMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("consumida", "Consumida"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="ativa",
                        max_length=12,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.CharField(blank=True, max_length=160)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="moda.materialficha",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="moda.ordemproducao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_moda",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de material",
                "verbose_name_plural": "Reservas de material",
                "db_table": "moda_reservas_material",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["filial", "status"],
                        name="moda_reserv_filial__6dcbd9_idx",
                    ),
                    models.Index(
                        fields=["ordem"], name="moda_reserv_ordem_i_9344be_idx"
                    ),
                ],
            },
        ),
    ]
