# Generated by Django 6.0.4 on 2026-08-18 19:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0016_necessidade_materiais"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapaordem",
            name="maquina",
            field=models.CharField(
                blank=True,
                help_text="Máquina ou posto usado nesta etapa. Ex.: Overloque 3, Calandra 1.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="etapaordem",
            name="tempo_minutos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minutos efetivamente gastos. Em branco, ninguém cronometrou.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Tempo gasto (min)",
            ),
        ),
    ]
