# Generated by Django 6.0.4 on 2026-08-18 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0017_terminal_setor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("inspetor", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                            ("retrabalho", "Retrabalho"),
                        ],
                        db_index=True,
                        default="em_andamento",
                        max_length=15,
                    ),
                ),
                ("quantidade_inspecionada", models.PositiveIntegerField(default=0)),
                ("quantidade_aprovada", models.PositiveIntegerField(default=0)),
                (
                    "quantidade_reprovada",
                    models.PositiveIntegerField(
                        default=0, help_text="Refugo: peça que não volta."
                    ),
                ),
                (
                    "quantidade_retrabalho",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Peça que volta para a produção e ainda pode ser vendida.",
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Obrigatório em reprovação e retrabalho — é o que permite corrigir a causa.",
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "aplicada_no_fluxo",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Se os números já foram levados para a etapa de Qualidade da ordem.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspecoes_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspecoes",
                        to="moda.ordemproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspeção de qualidade",
                "verbose_name_plural": "Inspeções de qualidade",
                "db_table": "moda_inspecoes",
                "ordering": ["-data", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemInspecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ponto",
                    models.CharField(
                        choices=[
                            ("tamanho", "Tamanho correto"),
                            ("cor", "Cor correta"),
                            ("costura", "Costura correta"),
                            ("estampa", "Estampa correta"),
                            ("numero", "Número correto"),
                            ("nome", "Nome correto"),
                            ("acabamento", "Acabamento"),
                            ("limpeza", "Limpeza"),
                            ("embalagem", "Embalagem"),
                        ],
                        max_length=15,
                    ),
                ),
                ("ordem_exibicao", models.PositiveSmallIntegerField(default=0)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendente", "Não avaliado"),
                            ("conforme", "Conforme"),
                            ("nao_conforme", "Não conforme"),
                            ("nao_aplica", "Não se aplica"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=200)),
                (
                    "inspecao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="moda.inspecao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto do checklist",
                "verbose_name_plural": "Pontos do checklist",
                "db_table": "moda_inspecoes_itens",
                "ordering": ["ordem_exibicao"],
            },
        ),
        migrations.AddIndex(
            model_name="inspecao",
            index=models.Index(
                fields=["filial", "status"], name="moda_inspec_filial__11541a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inspecao",
            index=models.Index(fields=["ordem"], name="moda_inspec_ordem_i_5089d3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="inspecao",
            unique_together={("filial", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="iteminspecao",
            unique_together={("inspecao", "ponto")},
        ),
    ]
