# Generated by Django 6.0.4 on 2026-08-18 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
        ("moda", "0018_qualidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Token do código de barras/QR. Diferente do número, de propósito.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("producao", "Produção Concluída"),
                            ("conferencia", "Conferência"),
                            ("separacao", "Separação"),
                            ("embalagem", "Embalagem"),
                            ("despacho", "Despacho"),
                            ("entrega", "Entrega"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="producao",
                        max_length=15,
                    ),
                ),
                ("data_conferencia", models.DateTimeField(blank=True, null=True)),
                ("data_separacao", models.DateTimeField(blank=True, null=True)),
                ("data_embalagem", models.DateTimeField(blank=True, null=True)),
                ("data_despacho", models.DateTimeField(blank=True, null=True)),
                ("data_entrega", models.DateTimeField(blank=True, null=True)),
                ("conferido_por", models.CharField(blank=True, max_length=80)),
                ("transportadora", models.CharField(blank=True, max_length=120)),
                ("rastreio", models.CharField(blank=True, max_length=60)),
                (
                    "recebido_por",
                    models.CharField(
                        blank=True,
                        help_text="Quem assinou o recebimento.",
                        max_length=120,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedicoes_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedicoes",
                        to="moda.ordemproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expedição",
                "verbose_name_plural": "Expedições",
                "db_table": "moda_expedicoes",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemConferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "expedicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conferencia",
                        to="moda.expedicao",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conferencias_moda",
                        to="moda.tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item conferido",
                "verbose_name_plural": "Itens conferidos",
                "db_table": "moda_expedicao_conferencia",
                "ordering": ["tamanho__ordem", "tamanho__sigla"],
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, editable=False, max_length=16, unique=True
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=160)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expedicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="moda.expedicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volume",
                "verbose_name_plural": "Volumes",
                "db_table": "moda_expedicao_volumes",
                "ordering": ["numero"],
            },
        ),
        migrations.AddIndex(
            model_name="expedicao",
            index=models.Index(
                fields=["filial", "status"], name="moda_expedi_filial__92e96b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expedicao",
            index=models.Index(fields=["ordem"], name="moda_expedi_ordem_i_20df79_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="expedicao",
            unique_together={("filial", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="itemconferencia",
            unique_together={("expedicao", "tamanho")},
        ),
        migrations.AlterUniqueTogether(
            name="volume",
            unique_together={("expedicao", "numero")},
        ),
    ]
