# Generated by Django 6.0.4 on 2026-08-19 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0021_codigo_qr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AprovacaoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liberado_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("observacao_interna", models.TextField(blank=True)),
                (
                    "resposta",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando o cliente"),
                            ("aprovado", "Aprovado pelo cliente"),
                            ("ajuste", "Cliente pediu ajuste"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=10,
                    ),
                ),
                (
                    "respondido_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("respondido_por", models.CharField(blank=True, max_length=120)),
                ("ip_resposta", models.GenericIPAddressField(blank=True, null=True)),
                ("motivo_ajuste", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "liberado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_moda_liberados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovacao",
                        to="moda.pedidoproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprovação do pedido",
                "verbose_name_plural": "Aprovações do pedido",
                "db_table": "moda_aprovacoes_pedido",
            },
        ),
    ]
