"""
As duas pontes que faltavam: requisição → compras, corte → estoque.

Dois campos, nenhum obrigatório e nenhum com valor calculado: linha
existente recebe NULL e a migration roda em tempo constante. Importa
porque ela roda como release command.
"""
# Generated by Django 6.0.4 on 2026-08-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Aponta para a ÚLTIMA migration REAL de compras, e não para a que o
        # `makemigrations` quis criar junto: aquela carrega mudanças de
        # modelo de outro trabalho, ainda inacabado, que remove campos e
        # constraints. A chave estrangeira daqui só precisa que a tabela
        # `PedidoCompra` exista, e ela existe desde a 0001.
        ('compras', '0017_remove_constraints_indexes'),
        ('moda', '0022_aprovacao_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocorte',
            name='estoque_baixado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='requisicaomaterial',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_moda', to='compras.pedidocompra'),
        ),
    ]
