"""
Vínculo do produto de moda com o produto do catálogo do ERP.

Campo opcional, sem valor calculado: linha existente recebe NULL e a
migration roda em tempo constante. Importa porque ela roda como release
command, e migration demorada em tabela grande derruba o deploy.
"""
# Generated by Django 6.0.4 on 2026-08-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0023_integracao_compras_estoque"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtomoda",
            name="produto_erp",
            field=models.ForeignKey(
                blank=True,
                help_text="Produto do catálogo do ERP que originou este.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos_moda",
                to="produtos.produto",
            ),
        ),
    ]
