# Generated by Django 6.0.4 on 2026-08-19 23:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0025_status_aguardando_aprovacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArquivoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="moda/pedidos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "gif",
                                    "webp",
                                    "svg",
                                    "pdf",
                                    "cdr",
                                    "ai",
                                    "eps",
                                    "psd",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "txt",
                                    "zip",
                                    "rar",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("arte", "Arte / layout"),
                            ("referencia", "Referência do cliente"),
                            ("documento", "Documento"),
                            ("outro", "Outro"),
                        ],
                        default="arte",
                        max_length=20,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True,
                        help_text="O que é este arquivo. Ex.: escudo em curva, planilha de nomes.",
                        max_length=160,
                    ),
                ),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arquivos_moda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos",
                        to="moda.pedidoproducao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo do pedido",
                "verbose_name_plural": "Arquivos do pedido",
                "db_table": "moda_pedido_arquivos",
                "ordering": ["-enviado_em"],
            },
        ),
    ]
