# Generated by Django 6.0.4 on 2026-08-20 14:24

import apps.moda.models.arquivo
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0026_arquivos_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivopedido",
            name="arquivo",
            field=models.FileField(
                upload_to=apps.moda.models.arquivo.caminho_do_arquivo,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "webp",
                            "svg",
                            "pdf",
                            "cdr",
                            "ai",
                            "eps",
                            "psd",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "txt",
                            "zip",
                            "rar",
                        ]
                    )
                ],
            ),
        ),
    ]
