# Generated by Django 5.2.17 on 2026-08-22 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0032_item_pedido_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstruturaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        help_text="Quantas unidades do componente entram em UMA unidade do produto.",
                        max_digits=10,
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordem de leitura na estrutura."
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=160)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "componente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usado_em",
                        to="moda.produtomoda",
                    ),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="componentes",
                        to="moda.produtomoda",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente da estrutura",
                "verbose_name_plural": "Estrutura do produto",
                "db_table": "moda_estrutura_produto",
                "ordering": ["ordem", "id"],
                "unique_together": {("pai", "componente")},
            },
        ),
    ]
