# Generated by Django 5.2.17 on 2026-08-22 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0033_estrutura_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenciaPessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conferido_em", models.DateTimeField(auto_now_add=True)),
                ("conferido_por", models.CharField(blank=True, max_length=80)),
                (
                    "expedicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conferencia_pessoas",
                        to="moda.expedicao",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conferencias",
                        to="moda.personalizacaoindividual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa conferida",
                "verbose_name_plural": "Pessoas conferidas",
                "db_table": "moda_expedicao_conferencia_pessoa",
                "ordering": ["individual__ordem", "individual_id"],
                "unique_together": {("expedicao", "individual")},
            },
        ),
    ]
