# Generated by Django 5.2.17 on 2026-08-23 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0034_conferencia_por_pessoa"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecido",
            name="produto_estoque",
            field=models.ForeignKey(
                blank=True,
                help_text="Ligue para o sistema ler o saldo em metros. A unidade precisa ser a mesma — não há conversão.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecidos_moda",
                to="produtos.produto",
                verbose_name="Produto no estoque",
            ),
        ),
    ]
