# Generated by Django 6.0.4 on 2026-08-24 16:34

import apps.moda.models.expedicao
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0035_tecido_produto_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedicao",
            name="assinado_documento",
            field=models.CharField(
                blank=True,
                help_text="CPF ou RG de quem assinou, quando informado.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="expedicao",
            name="assinado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expedicao",
            name="assinatura",
            field=models.ImageField(
                blank=True,
                help_text="Traço do cliente no recebimento.",
                null=True,
                upload_to=apps.moda.models.expedicao.caminho_da_assinatura,
            ),
        ),
    ]
