# Generated by Django 5.2.17 on 2026-08-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0012_alter_movimentacaoestoque_documento_tipo"),
        ("moda", "0036_assinatura_de_entrega"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumoLoteCorte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "custo_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "corte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos_lote",
                        to="moda.registrocorte",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vazio quando os lotes não cobriram o consumo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumos_corte",
                        to="estoque.loteproduto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo de lote no corte",
                "verbose_name_plural": "Consumos de lote no corte",
                "db_table": "moda_consumos_lote_corte",
                "ordering": ["pk"],
                "indexes": [
                    models.Index(
                        fields=["corte"], name="moda_consum_corte_i_cd29c3_idx"
                    ),
                    models.Index(
                        fields=["lote"], name="moda_consum_lote_id_a6e062_idx"
                    ),
                ],
            },
        ),
    ]
