# Generated by Django 5.2.17 on 2026-08-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0037_consumo_lote_corte"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemproducao",
            name="material_reservado_em",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
