# Generated by Codex on 2026-08-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0053_limpar_configuracoes_eureka_de_outras_empresas"),
        ("moda", "0038_reserva_ao_iniciar"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoproducao",
            name="conta_bancaria_entrada",
            field=models.ForeignKey(
                blank=True,
                help_text="Conta onde a entrada do pedido foi recebida.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_moda_entradas",
                to="financeiro.contabancaria",
            ),
        ),
    ]
