# Generated by Django 5.2.17 on 2026-08-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0042_tipo_impressao_e_multiplos_visuais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacao',
            name='tecnica',
            field=models.CharField(choices=[('sublimacao', 'Sublimação'), ('silk', 'Silk'), ('bordado', 'Bordado'), ('dtf', 'DTF'), ('dtg', 'DTG'), ('transfer', 'Transfer'), ('patch', 'Patch'), ('sem_impressao', 'Sem impressão'), ('outro', 'Outro')], default='sublimacao', max_length=120),
        ),
    ]
