# Generated by Django 5.2.17 on 2026-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moda', '0048_historico_criacao_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacao',
            name='tecnica',
            field=models.CharField(choices=[('sublimacao', 'Sublimação'), ('silk', 'Silk'), ('bordado', 'Bordado'), ('dtf', 'DTF'), ('dtg', 'DTG'), ('transfer', 'Transfer'), ('patch', 'Patch'), ('relevo', 'Relevo'), ('sem_impressao', 'Sem impressão'), ('outro', 'Outro')], default='sublimacao', max_length=120),
        ),
        migrations.AlterField(
            model_name='produtomoda',
            name='tipo_impressao',
            field=models.CharField(blank=True, choices=[('sublimacao', 'Sublimação'), ('silk', 'Silk'), ('bordado', 'Bordado'), ('dtf', 'DTF'), ('dtg', 'DTG'), ('transfer', 'Transfer'), ('patch', 'Patch'), ('relevo', 'Relevo'), ('sem_impressao', 'Sem impressão'), ('outro', 'Outro')], help_text='Padrão de impressão carregado automaticamente ao usar este modelo na OP.', max_length=20, verbose_name='Tipo de impressão'),
        ),
    ]
