# Generated by Django 6.0.4 on 2026-09-03 13:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0054_imagem_rascunho_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichatecnica",
            name="peso_peca_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Quanto pesa UMA peça acabada, em gramas. Ex.: 240,5. Serve para frete, expedição e para conferir o rendimento do tecido.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Peso da peça pronta (g)",
            ),
        ),
    ]
