# Generated by Django 6.0.4 on 2026-09-03 16:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0055_peso_da_peca_pronta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichatecnica",
            name="peso_peca_g",
        ),
        migrations.CreateModel(
            name="PesoTamanhoFicha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peso_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Peso (g)",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesos_tamanho",
                        to="moda.fichatecnica",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="moda.grade",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="moda.tamanho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peso por tamanho",
                "verbose_name_plural": "Pesos por tamanho",
                "db_table": "moda_fichas_pesos_tamanho",
                "ordering": ["grade__nome", "ordem", "id"],
                "unique_together": {("ficha", "grade", "tamanho")},
            },
        ),
    ]
