# Generated by Django 5.2.17 on 2026-09-09 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_funcionario'),
        ('core', '0062_separacao_filial_segura'),
        ('moda', '0057_lixeira_itens_op'),
        ('produtos', '0031_produto_tempo_preparo_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=80)),
                ('observacao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('linha', 'Linha'), ('elastico', 'Elástico'), ('ziper', 'Zíper'), ('botao', 'Botão'), ('etiqueta', 'Etiqueta'), ('tag', 'Tag'), ('embalagem', 'Embalagem'), ('aviamento', 'Outro aviamento')], max_length=20)),
                ('codigo', models.CharField(blank=True, help_text='Código no estoque ou no fornecedor.', max_length=40)),
                ('unidade', models.CharField(choices=[('m', 'm'), ('cm', 'cm'), ('kg', 'kg'), ('g', 'g'), ('un', 'un'), ('par', 'par'), ('pc', 'pç'), ('rolo', 'rolo'), ('cone', 'cone')], default='un', max_length=6)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aviamentos_moda', to='cadastros.fornecedor')),
                ('produto_estoque', models.ForeignKey(blank=True, help_text='Ligue para o sistema conferir saldo e permitir reserva. A unidade precisa ser a mesma — não há conversão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aviamentos_moda', to='produtos.produto', verbose_name='Produto no estoque')),
            ],
            options={
                'verbose_name': 'Aviamento',
                'verbose_name_plural': 'Aviamentos',
                'db_table': 'moda_aviamentos',
                'ordering': ['tipo', 'nome'],
                'abstract': False,
                'unique_together': {('filial', 'nome')},
            },
        ),
    ]
