# Generated by Django 5.2.17 on 2026-09-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moda", "0058_aviamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviamento",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="cor",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="linha",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="marca",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="modelo",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="tecido",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
    ]
