# Generated by Django 5.2.16 on 2026-07-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_parametrossistema_focusnfe_token_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_regime_tributario',
            field=models.SmallIntegerField(choices=[(1, '1 - Simples Nacional'), (2, '2 - Simples Nacional com excesso de sublimite'), (3, '3 - Regime Normal'), (4, '4 - Simples Nacional - MEI')], help_text='CRT do emitente: 1=SN, 2=SN excesso, 3=Normal, 4=MEI.'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='codigo_regime_tributario',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 - Simples Nacional'), (2, '2 - Simples Nacional com excesso de sublimite'), (3, '3 - Regime Normal'), (4, '4 - Simples Nacional - MEI')], help_text='CRT do emitente. Se vazio, usa o codigo da empresa.', null=True),
        ),
    ]
