# Generated by Django 6.0.4 on 2026-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_criar_tabela_registros_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrossistema',
            name='certificado_base64',
            field=models.TextField(blank=True, default='', help_text='Conteúdo do certificado A1 codificado em base64. Preenchido automaticamente ao fazer upload. Persiste entre redeploys (diferente do FileField).'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='modulo',
            field=models.CharField(choices=[('vendas', 'Vendas'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('fiscal', 'Fiscal'), ('config', 'Configurações'), ('relatorios', 'Relatórios'), ('pdv', 'PDV'), ('producao', 'Produção'), ('qualidade', 'Qualidade'), ('compras', 'Compras'), ('cadastros', 'Cadastros'), ('produtos', 'Produtos'), ('logistica', 'Logistica'), ('cashback', 'Cashback')], max_length=60),
        ),
    ]
