# Generated by Django 6.0.4 on 2026-07-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_filial_coordenadas_geo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("vendas", "Vendas"),
                    ("estoque", "Estoque"),
                    ("financeiro", "Financeiro"),
                    ("fiscal", "Fiscal"),
                    ("config", "Configurações"),
                    ("relatorios", "Relatórios"),
                    ("pdv", "PDV"),
                    ("producao", "Produção"),
                    ("qualidade", "Qualidade"),
                    ("compras", "Compras"),
                    ("cadastros", "Cadastros"),
                    ("produtos", "Produtos"),
                    ("logistica", "Logistica"),
                    ("cashback", "Cashback"),
                    ("crm", "CRM"),
                    ("mapas", "Mapas e Geolocalização"),
                ],
                max_length=60,
            ),
        ),
    ]
