# Generated by Django 6.0.4 on 2026-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_limpar_sondagens_geo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="geo_atualizado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="geo_endereco_hash",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name="empresa",
            name="geo_erro",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="empresa",
            name="geo_fixado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="geo_precisao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exata", "Exata (número)"),
                    ("aproximada", "Aproximada (rua/bairro)"),
                    ("cidade", "Centro da cidade"),
                    ("manual", "Ajustada manualmente"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
