# Generated by Django 6.0.4 on 2026-08-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_permissao_modulo_food_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transferencia_recebida", "Transferencia recebida"),
                    ("transferencia_conferida", "Transferencia conferida"),
                    ("alerta_sistema", "Alerta do sistema"),
                    ("food_pedido_recebido", "Pedido recebido na cozinha"),
                    ("food_pedido_iniciado", "Pedido em preparo"),
                    ("food_pedido_pronto", "Pedido pronto"),
                    ("food_pedido_entregue", "Pedido entregue"),
                    ("food_item_cancelado", "Item cancelado na cozinha"),
                    ("food_item_atrasado", "Item atrasado na cozinha"),
                    ("food_produto_indisponivel", "Produto indisponível"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
