# Generated by Django 6.0.4 on 2026-08-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_filial_modulos_desativados"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="modulos_extras",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Módulos liberados manualmente, além dos que o segmento já concede.",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="segmento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("moda_confeccao", "Moda / Confecção"),
                    ("industria_alimenticia", "Indústria Alimentícia"),
                    ("comercio", "Comércio"),
                    ("distribuidora", "Distribuidora"),
                    ("atacado", "Atacado"),
                    ("varejo", "Varejo"),
                    ("polpa_frutas", "Polpa de Frutas"),
                    ("padarias", "Padarias"),
                    ("embalagens", "Embalagens"),
                ],
                help_text="Libera automaticamente os módulos especializados do vertical.",
                max_length=30,
            ),
        ),
    ]
