"""
Os sete tipos de alerta do vertical Moda entram em `Notificacao.Tipo`.

Só mexe em `choices`, que o Django valida em Python e não vira restrição
no banco: nenhuma linha existente é tocada e a migration roda em tempo
constante -- importante porque ela roda como release command, e migration
demorada em tabela grande derruba o deploy.
"""
# Generated by Django 6.0.4 on 2026-08-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_preservar_food_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transferencia_recebida", "Transferencia recebida"),
                    ("transferencia_conferida", "Transferencia conferida"),
                    ("alerta_sistema", "Alerta do sistema"),
                    ("food_pedido_recebido", "Pedido recebido na cozinha"),
                    ("food_pedido_iniciado", "Pedido em preparo"),
                    ("food_pedido_pronto", "Pedido pronto"),
                    ("food_pedido_entregue", "Pedido entregue"),
                    ("food_item_cancelado", "Item cancelado na cozinha"),
                    ("food_item_atrasado", "Item atrasado na cozinha"),
                    ("food_produto_indisponivel", "Produto indisponível"),
                    ("moda_pedido_atrasado", "Moda: pedido atrasado"),
                    ("moda_pedido_vencendo", "Moda: pedido perto do prazo"),
                    ("moda_material_insuficiente", "Moda: material insuficiente"),
                    ("moda_producao_abaixo", "Moda: produção abaixo do planejado"),
                    ("moda_setor_sobrecarregado", "Moda: setor sobrecarregado"),
                    ("moda_rejeicao_alta", "Moda: alto índice de rejeição"),
                    (
                        "moda_aproveitamento_baixo",
                        "Moda: baixo aproveitamento de corte",
                    ),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
