"""
As sete áreas do vertical Moda entram em `Permissao.Modulo`.

Só mexe em `choices` — validação em Python, nenhuma restrição no banco:
nenhuma linha é tocada e a migration roda em tempo constante. Importa
porque ela roda como release command, e migration demorada em tabela
grande derruba o deploy.

Nenhum perfil existente muda aqui. Quem tem `moda` continua tendo tudo,
pelo guarda-chuva em `Usuario.tem_permissao`; as áreas só passam a valer
nos perfis criados com elas.
"""
# Generated by Django 6.0.4 on 2026-08-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alertas_moda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("vendas", "Vendas"),
                    ("estoque", "Estoque"),
                    ("financeiro", "Financeiro"),
                    ("fiscal", "Fiscal"),
                    ("config", "Configurações"),
                    ("relatorios", "Relatórios"),
                    ("pdv", "PDV"),
                    ("producao", "Produção"),
                    ("qualidade", "Qualidade"),
                    ("compras", "Compras"),
                    ("cadastros", "Cadastros"),
                    ("produtos", "Produtos"),
                    ("logistica", "Logistica"),
                    ("cashback", "Cashback"),
                    ("crm", "CRM"),
                    ("mapas", "Mapas e Geolocalização"),
                    ("food_service", "Food Service"),
                    ("moda", "Moda e Confecção"),
                    ("moda_comercial", "Moda: Comercial"),
                    ("moda_pcp", "Moda: PCP"),
                    ("moda_corte", "Moda: Corte"),
                    ("moda_producao", "Moda: Produção"),
                    ("moda_qualidade", "Moda: Qualidade"),
                    ("moda_expedicao", "Moda: Expedição"),
                    ("moda_indicadores", "Moda: Indicadores"),
                ],
                max_length=60,
            ),
        ),
    ]
