# Generated by Django 5.2.17 on 2026-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_areas_moda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('visualizar', 'Visualizar'), ('criar', 'Criar'), ('editar', 'Editar'), ('aprovar', 'Aprovar'), ('cancelar', 'Cancelar'), ('exportar', 'Exportar'), ('efetivar', 'Efetivar'), ('vincular', 'Vincular'), ('reprocessar', 'Reprocessar'), ('ajustar', 'Ajustar'), ('transferir', 'Transferir'), ('inventariar', 'Inventariar'), ('baixar_validade', 'Baixar validade'), ('excluir', 'Excluir'), ('restaurar', 'Restaurar')], db_index=True, max_length=40),
        ),
    ]
