"""
Mais um tipo em `Notificacao.Tipo`: o cliente pediu ajuste na arte.

Como a 0048, so mexe em `choices` -- validacao em Python, nada de restricao
no banco. Nenhuma linha existente e tocada e a migration roda em tempo
constante, o que importa porque ela roda como release command: migration
demorada em tabela grande derruba o deploy.
"""
# Generated by Django 5.2.17 on 2026-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_registroauditoria_acao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("transferencia_recebida", "Transferencia recebida"),
                    ("transferencia_conferida", "Transferencia conferida"),
                    ("alerta_sistema", "Alerta do sistema"),
                    ("food_pedido_recebido", "Pedido recebido na cozinha"),
                    ("food_pedido_iniciado", "Pedido em preparo"),
                    ("food_pedido_pronto", "Pedido pronto"),
                    ("food_pedido_entregue", "Pedido entregue"),
                    ("food_item_cancelado", "Item cancelado na cozinha"),
                    ("food_item_atrasado", "Item atrasado na cozinha"),
                    ("food_produto_indisponivel", "Produto indisponível"),
                    ("moda_pedido_atrasado", "Moda: pedido atrasado"),
                    ("moda_pedido_vencendo", "Moda: pedido perto do prazo"),
                    ("moda_material_insuficiente", "Moda: material insuficiente"),
                    ("moda_producao_abaixo", "Moda: produção abaixo do planejado"),
                    ("moda_setor_sobrecarregado", "Moda: setor sobrecarregado"),
                    ("moda_rejeicao_alta", "Moda: alto índice de rejeição"),
                    (
                        "moda_aproveitamento_baixo",
                        "Moda: baixo aproveitamento de corte",
                    ),
                    ("moda_cliente_ajuste", "Moda: cliente pediu ajuste"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
