# Generated by Django 5.2.17 on 2026-08-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_food_service_so_padaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("compras", "Compras"),
                    ("estoque", "Estoque"),
                    ("financeiro", "Financeiro"),
                    ("logistica", "Logística"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
