# Generated by Django 5.2.17 on 2026-08-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auditoria_modulo_logistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='controlar_entrega_contas_receber',
            field=models.BooleanField(default=False, help_text='Exibe situação e previsão de entrega somente nesta filial. Não altera pagamentos.', verbose_name='Acompanhar entrega no contas a receber'),
        ),
    ]
