# Generated by Django 5.2.17 on 2026-09-06 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_usuario_preferencias_tabelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('db_alias', models.SlugField(max_length=80, unique=True)),
                ('database_url_env_var', models.CharField(blank=True, max_length=120)),
                ('railway_database_service_id', models.CharField(blank=True, max_length=120)),
                ('railway_database_service_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_configuracao', 'Aguardando configuração'), ('configurado', 'Configurado'), ('ativo', 'Ativo'), ('erro', 'Erro'), ('inativo', 'Inativo')], db_index=True, default='pendente', max_length=32)),
                ('provisionamento_modo', models.CharField(default='manual', max_length=30)),
                ('provisionamento_solicitado_em', models.DateTimeField(blank=True, null=True)),
                ('provisionado_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_migracao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_verificacao_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banco_dedicado', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Banco da empresa',
                'verbose_name_plural': 'Bancos das empresas',
                'db_table': 'empresas_bancos',
                'ordering': ['empresa__razao_social'],
            },
        ),
    ]
