# Generated by Django 5.2.17 on 2026-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_empresa_banco_multitenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPublicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=24)),
                ('token_hash', models.CharField(max_length=64)),
                ('db_alias', models.SlugField(max_length=80)),
            ],
            options={
                'db_table': 'tenant_public_links',
                'constraints': [models.UniqueConstraint(fields=('tipo', 'token_hash'), name='uq_tenant_public_link_tipo_hash')],
            },
        ),
    ]
