# Generated by Django 5.2.17 on 2026-09-08 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_rename_railway_project_pool_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparacaoFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('simulado', 'Simulado'), ('bloqueado', 'Bloqueado'), ('executando', 'Executando'), ('concluido', 'Concluído'), ('erro', 'Erro')], db_index=True, default='rascunho', max_length=20)),
                ('plano_json', models.JSONField(blank=True, default=dict)),
                ('simulacao_json', models.JSONField(blank=True, default=dict)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
                ('backup_exportacao_path', models.CharField(blank=True, max_length=500)),
                ('etapa_atual', models.CharField(blank=True, max_length=120)),
                ('progresso_percentual', models.PositiveSmallIntegerField(default=0)),
                ('executor_backend', models.CharField(blank=True, max_length=30)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('despachado_em', models.DateTimeField(blank=True, null=True)),
                ('relatorio_json', models.JSONField(blank=True, default=dict)),
                ('rollback_json', models.JSONField(blank=True, default=dict)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('banco_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_filial', to='core.empresabanco')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('empresa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_destino', to='core.empresa')),
                ('empresa_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separacoes_origem', to='core.empresa')),
                ('filial_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separacoes', to='core.filial')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Separação de filial',
                'verbose_name_plural': 'Separações de filiais',
                'db_table': 'separacoes_filiais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['filial_origem', 'status'], name='separacoes__filial__677fda_idx'), models.Index(fields=['empresa_origem', '-created_at'], name='separacoes__empresa_42d6bf_idx')],
            },
        ),
    ]
