# Generated by Django 5.2.17 on 2026-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_separacao_filial_segura'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regime_ibs_cbs',
            field=models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], help_text='Apuracao de IBS/CBS. Em branco, o sistema usa o padrao do regime empresarial.', max_length=10),
        ),
        migrations.AddField(
            model_name='filial',
            name='regime_ibs_cbs',
            field=models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], help_text='Regime IBS/CBS especifico da filial. Se vazio, usa o cadastro da empresa.', max_length=10),
        ),
    ]
