# Generated by Django 5.2.17 on 2026-09-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_parametrossistema_checkout_busca_nome_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacesso',
            name='alcada_transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo (R$) que este perfil pode transferir entre filiais sem precisar de aprovação de um perfil com alçada maior. Vazio = sem limite (perfis admin sempre executam direto, independente deste campo).', max_digits=12, null=True),
        ),
    ]
