# Generated by Django 5.2.17 on 2026-09-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_perfilacesso_alcada_transferencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("compras", "Compras"),
                    ("estoque", "Estoque"),
                    ("financeiro", "Financeiro"),
                    ("logistica", "Logística"),
                    ("produtos", "Produtos"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
