# Generated by Django 5.2.17 on 2026-10-08 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_parametrossistema_balanca_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='resumo_whatsapp_ativo',
            field=models.BooleanField(default=False, help_text='Autoriza o iTED a enviar o desempenho do dia anterior aos destinatários cadastrados nesta filial.', verbose_name='Receber resumo diário pelo WhatsApp'),
        ),
        migrations.AddField(
            model_name='parametrossistema',
            name='resumo_whatsapp_incluir_agenda',
            field=models.BooleanField(default=False, help_text='Ative apenas para filiais que trabalham com agendamentos.', verbose_name='Incluir indicadores da agenda'),
        ),
        migrations.AlterField(
            model_name='railwayprojectpool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='DestinatarioResumoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posicao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(help_text='Somente números. Exemplo: 5584999990000.', max_length=13, validators=[django.core.validators.RegexValidator('^\\d{10,13}$', 'Informe somente números, com DDD e, de preferência, o código 55.')])),
                ('ativo', models.BooleanField(default=True)),
                ('parametros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_resumo_whatsapp', to='core.parametrossistema')),
            ],
            options={
                'db_table': 'parametros_resumo_whatsapp_destinatarios',
                'ordering': ['posicao', 'id'],
                'constraints': [models.UniqueConstraint(fields=('parametros', 'posicao'), name='resumo_whatsapp_destinatario_posicao_unica')],
            },
        ),
    ]
