# Generated by Django 6.0.4 on 2026-07-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0011_alter_creditocliente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditocliente",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Crédito de Cliente",
                "verbose_name_plural": "Créditos de Clientes",
            },
        ),
        migrations.AlterField(
            model_name="creditocliente",
            name="status",
            field=models.CharField(
                choices=[
                    ("disponivel", "Disponível"),
                    ("utilizado", "Utilizado"),
                    ("cancelado", "Cancelado"),
                ],
                db_index=True,
                default="disponivel",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditocliente",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor total do crédito gerado.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="creditocliente",
            name="valor_utilizado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor já utilizado do crédito.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="documentofiscal",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("nfe", "NF-e"),
                    ("nfce", "NFC-e"),
                    ("nfse", "NFS-e"),
                    ("cte", "CT-e"),
                    ("mdfe", "MDF-e"),
                ],
                max_length=10,
            ),
        ),
    ]
