# Generated by Django 6.0.4 on 2026-07-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0012_mdfe_tipo_documento_fiscal"),
    ]

    operations = [
        migrations.AddField(
            model_name="formapagamento",
            name="movimenta_caixa",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para formas como Doação/Permuta: a venda continua dando baixa no estoque normalmente, mas o valor não entra no total do caixa nem no financeiro.",
            ),
        ),
    ]
