# Generated by Django 6.0.4 on 2026-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_formapagamento_movimenta_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='tipo',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('cheque', 'Cheque'), ('ted', 'TED'), ('doc', 'DOC'), ('vale', 'Vale'), ('convenio', 'Convênio'), ('crediario', 'Crediário'), ('cashback', 'Cashback')], max_length=30),
        ),
    ]
