# Generated by Django 5.2.17 on 2026-08-20 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_formas_e_pagamentos_existentes(apps, schema_editor):
    ContaPagar = apps.get_model('financeiro', 'ContaPagar')
    Pagamento = apps.get_model('financeiro', 'PagamentoContaPagar')

    for conta in ContaPagar.objects.all().iterator(chunk_size=500):
        if conta.forma_pagamento_id:
            conta.forma_pagamento_prevista_id = conta.forma_pagamento_id

        possui_pagamento = conta.valor_pago and conta.valor_pago > 0 and conta.data_pagamento
        if possui_pagamento:
            Pagamento.objects.create(
                filial_id=conta.filial_id,
                conta_pagar_id=conta.pk,
                data_pagamento=conta.data_pagamento,
                valor_pago=conta.valor_pago,
                valor_juros=conta.valor_juros,
                valor_multa=conta.valor_multa,
                valor_desconto=conta.valor_desconto,
                forma_pagamento_id=conta.forma_pagamento_id,
                conta_bancaria_id=conta.conta_bancaria_id,
                comprovante_url=conta.comprovante_url,
                observacao='Registro consolidado migrado do histórico anterior.',
                usuario_id=conta.usuario_pagamento_id,
            )
        else:
            conta.forma_pagamento_id = None
            conta.conta_bancaria_id = None

        conta.save(update_fields=[
            'forma_pagamento_prevista', 'forma_pagamento', 'conta_bancaria',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_areas_moda'),
        ('financeiro', '0020_contapagar_ajustar_vencimento_dia_util'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='forma_pagamento_prevista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.formapagamento'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.formapagamento'),
        ),
        migrations.CreateModel(
            name='PagamentoContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('comprovante_url', models.URLField(blank=True, max_length=500)),
                ('observacao', models.TextField(blank=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.contabancaria')),
                ('conta_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.contapagar')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_contas_pagar', to='core.filial')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.formapagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_contas_pagar_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagamentos_contas_pagar',
                'ordering': ['-data_pagamento', '-created_at'],
                'indexes': [models.Index(fields=['filial', 'data_pagamento'], name='pagamentos__filial__9f6f10_idx'), models.Index(fields=['conta_pagar', 'data_pagamento'], name='pagamentos__conta_p_f6b78b_idx')],
            },
        ),
        migrations.RunPython(
            migrar_formas_e_pagamentos_existentes,
            migrations.RunPython.noop,
        ),
    ]
