# Generated by Django 5.2.17 on 2026-08-20 18:34

import apps.financeiro.models.receber_pagar
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_pagamentos_conta_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='comprovante_arquivo',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.financeiro.models.receber_pagar.caminho_comprovante_pagamento, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'])]),
        ),
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='comprovante_nome_original',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
