# Generated by Django 5.2.17 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_contapagar_exclusao_logica'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='taxa_calculada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='taxa_fixa_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='taxa_percentual_aplicada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_liquido_recebido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_taxa_recebimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='taxa_fixa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo descontado em cada transação recebida.', max_digits=14),
        ),
    ]
