# Generated by Django 5.2.17 on 2026-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_contareceber_taxa_calculada_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxaparcelamento',
            options={'ordering': ['parcelas', 'bandeira']},
        ),
        migrations.AlterUniqueTogether(
            name='taxaparcelamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='prazo_compensacao_dias_uteis',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dias uteis entre a transacao e o credito na conta bancaria.'),
        ),
        migrations.AddField(
            model_name='taxaparcelamento',
            name='bandeira',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='taxaparcelamento',
            unique_together={('forma_pagamento', 'parcelas', 'bandeira')},
        ),
    ]
