# Generated by Django 5.2.17 on 2026-08-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0029_configurar_taxas_eureka'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='data_liquidacao_prevista',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='prazo_compensacao_aplicado',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
