# Generated by Django 5.2.17 on 2026-08-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0044_tarifa_pagamento_e_links_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='intervalo_recorrencia_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='ajustar_vencimento_dia_util',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='frequencia_recorrencia',
            field=models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizada', 'Personalizada em dias')], max_length=15),
        ),
    ]
