# Generated by Django 5.2.17 on 2026-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0045_recorrencia_dias_e_vencimento_util'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='antecipar_vencimento_dia_util',
            field=models.BooleanField(default=False),
        ),
    ]
