# Generated by Django 5.2.17 on 2026-08-25 05:17

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_historico_recebimentos(apps, schema_editor):
    ContaReceber = apps.get_model('financeiro', 'ContaReceber')
    PagamentoContaReceber = apps.get_model('financeiro', 'PagamentoContaReceber')

    contas_com_baixa = ContaReceber.objects.filter(valor_pago__gt=Decimal('0'))
    for conta in contas_com_baixa.iterator():
        if PagamentoContaReceber.objects.filter(conta_receber_id=conta.pk).exists():
            continue

        data_pagamento = conta.data_pagamento or conta.data_vencimento
        valor_taxa = conta.valor_taxa_recebimento or Decimal('0')
        valor_liquido = conta.valor_liquido_recebido or (conta.valor_pago - valor_taxa)

        PagamentoContaReceber.objects.create(
            filial_id=conta.filial_id,
            conta_receber_id=conta.pk,
            data_pagamento=data_pagamento,
            valor_pago=conta.valor_pago,
            valor_juros=conta.valor_juros or Decimal('0'),
            valor_multa=conta.valor_multa or Decimal('0'),
            valor_desconto=conta.valor_desconto or Decimal('0'),
            valor_taxa=valor_taxa,
            valor_liquido=valor_liquido,
            forma_pagamento_id=conta.forma_pagamento_id,
            conta_bancaria_id=conta.conta_bancaria_id,
            bandeira=conta.bandeira_recebimento or '',
            numero_parcelas=conta.parcelas_recebimento,
            observacao='Historico criado a partir da baixa existente.',
            usuario_id=conta.usuario_baixa_id,
        )

    ContaReceber.objects.filter(
        valor_pago__gt=Decimal('0'),
        valor_saldo__gt=Decimal('0'),
        status__in=['aberto', 'vencido', 'negociado'],
    ).update(status='pago_parcial')


def remover_historico_recebimentos(apps, schema_editor):
    PagamentoContaReceber = apps.get_model('financeiro', 'PagamentoContaReceber')
    PagamentoContaReceber.objects.filter(
        observacao='Historico criado a partir da baixa existente.',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alerta_cliente_ajuste'),
        ('financeiro', '0049_reforcar_tarifas_saida_orenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('pago_parcial', 'Pago parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('negociado', 'Adiado'), ('devolvido', 'Devolvido')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='metadespesapessoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='PagamentoContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_taxa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bandeira', models.CharField(blank=True, default='', max_length=20)),
                ('numero_parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.contabancaria')),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.contareceber')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_contas_receber', to='core.filial')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financeiro.formapagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_contas_receber_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagamentos_contas_receber',
                'ordering': ['-data_pagamento', '-created_at'],
                'indexes': [models.Index(fields=['filial', 'data_pagamento'], name='pagamentos__filial__8a56d3_idx'), models.Index(fields=['conta_receber', 'data_pagamento'], name='pagamentos__conta_r_61a741_idx')],
            },
        ),
        migrations.RunPython(criar_historico_recebimentos, remover_historico_recebimentos),
    ]
