# Generated by Django 5.2.17 on 2026-08-25 06:01

from django.db import migrations, models


def marcar_pagos_parciais(apps, schema_editor):
    ContaPagar = apps.get_model('financeiro', 'ContaPagar')
    ContaPagar.objects.filter(
        valor_pago__gt=0,
        valor_saldo__gt=0,
        status__in=['aberto', 'vencido', 'agendado'],
    ).update(status='pago_parcial')


def desfazer_pagos_parciais(apps, schema_editor):
    ContaPagar = apps.get_model('financeiro', 'ContaPagar')
    ContaPagar.objects.filter(status='pago_parcial').update(status='aberto')


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0050_alter_contareceber_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('pago_parcial', 'Pago parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('agendado', 'Agendado')], default='aberto', max_length=20),
        ),
        migrations.RunPython(marcar_pagos_parciais, desfazer_pagos_parciais),
    ]
