# Generated by Django 6.0.4 on 2026-08-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0055_formas_pagamento_padrao_das_filiais"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentofiscal",
            name="payload_envio",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
