# Generated by Django 5.2.17 on 2026-08-31 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auditoria_modulo_logistica'),
        ('financeiro', '0058_formapagamento_exibir_no_pdv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCaixaHistorico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.CharField(max_length=255)),
                ('arquivo_sha256', models.CharField(max_length=64)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caixa_historico_lotes',
            },
        ),
        migrations.CreateModel(
            name='DiaCaixaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('aba_origem', models.CharField(max_length=100)),
                ('conteudo_sha256', models.CharField(max_length=64)),
                ('saldo_anterior_informado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('saldo_final_informado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_entradas', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_saidas', models.DecimalField(decimal_places=2, max_digits=16)),
                ('observacoes', models.JSONField(blank=True, default=list)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias', to='financeiro.lotecaixahistorico')),
            ],
            options={
                'db_table': 'caixa_historico_dias',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_original', models.CharField(max_length=100)),
                ('celula_origem', models.CharField(max_length=16)),
                ('ordem', models.PositiveIntegerField()),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.diacaixahistorico')),
            ],
            options={
                'db_table': 'caixa_historico_movimentos',
                'ordering': ['dia__data', 'ordem', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='diacaixahistorico',
            constraint=models.UniqueConstraint(fields=('filial', 'data'), name='caixa_hist_filial_data_uniq'),
        ),
        migrations.AddConstraint(
            model_name='movimentocaixahistorico',
            constraint=models.UniqueConstraint(fields=('dia', 'celula_origem'), name='caixa_hist_dia_celula_uniq'),
        ),
        migrations.AddConstraint(
            model_name='movimentocaixahistorico',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='caixa_hist_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='movimentocaixahistorico',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['entrada', 'saida'])), name='caixa_hist_tipo_valido'),
        ),
    ]
