# Generated by Django 5.2.17 on 2026-08-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0059_caixa_historico_isolado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='previsao_entrega_complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='status_entrega',
            field=models.CharField(choices=[('sem_previsao', 'Sem previsão'), ('prevista', 'Prevista'), ('entregue', 'Entregue')], default='sem_previsao', max_length=20),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='documento_numero',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
