# Generated by Django 5.2.17 on 2026-09-02 02:40

from django.db import migrations, models


def preencher_tarifas_existentes(apps, schema_editor):
    Pagamento = apps.get_model('financeiro', 'PagamentoContaPagar')
    ContaPagar = apps.get_model('financeiro', 'ContaPagar')
    alias = schema_editor.connection.alias

    tarifas = {
        tarifa.documento_id: tarifa.valor_pago or tarifa.valor_final
        for tarifa in ContaPagar._base_manager.using(alias).filter(
            documento_tipo='taxa_pagamento',
            documento_id__isnull=False,
            excluido_em__isnull=True,
        )
    }
    for pagamento_id, valor in tarifas.items():
        Pagamento._base_manager.using(alias).filter(pk=pagamento_id).update(
            tarifa_bancaria=valor,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0062_marcar_transferencias_manuais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='tarifa_bancaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa efetivamente cobrada pelo banco neste pagamento.', max_digits=14, null=True),
        ),
        migrations.RunPython(preencher_tarifas_existentes, migrations.RunPython.noop),
    ]
