# Generated by Django 6.0.4 on 2026-08-06 19:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0014_vincular_rota_motorista_veiculo"),
        ("core", "0042_permissao_modulo_food_service"),
        ("pdv", "0009_vendapdv_delivery_encerrado_em"),
        ("produtos", "0030_itemtabelapreco_desconto_valor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome_ocupante", models.CharField(blank=True, max_length=100)),
                ("quantidade_pessoas", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("fechando", "Fechando"),
                            ("fechada", "Fechada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=20,
                    ),
                ),
                ("aberta_em", models.DateTimeField(auto_now_add=True)),
                ("fechada_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comandas",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "garcom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comandas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda_pdv",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comanda",
                        to="pdv.vendapdv",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comanda",
                "verbose_name_plural": "Comandas",
                "db_table": "food_service_comandas",
                "ordering": ["-aberta_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemComanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("adicionado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "comanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="food_service.comanda",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de comanda",
                "verbose_name_plural": "Itens de comanda",
                "db_table": "food_service_itens_comanda",
                "ordering": ["adicionado_em"],
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("numero", models.PositiveIntegerField()),
                ("nome", models.CharField(blank=True, max_length=60)),
                ("capacidade", models.PositiveIntegerField(default=4)),
                ("setor", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("livre", "Livre"),
                            ("ocupada", "Ocupada"),
                            ("reservada", "Reservada"),
                            ("aguardando_limpeza", "Aguardando limpeza"),
                            ("fechando_conta", "Fechando conta"),
                        ],
                        default="livre",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "verbose_name_plural": "Mesas",
                "db_table": "food_service_mesas",
                "ordering": ["numero"],
            },
        ),
        migrations.AddField(
            model_name="comanda",
            name="mesas",
            field=models.ManyToManyField(
                blank=True, related_name="comandas", to="food_service.mesa"
            ),
        ),
        migrations.AddConstraint(
            model_name="mesa",
            constraint=models.UniqueConstraint(
                fields=("filial", "numero"), name="uq_mesa_filial_numero"
            ),
        ),
    ]
