# Generated by Django 6.0.4 on 2026-08-06 19:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_service", "0002_reserva"),
        ("produtos", "0030_itemtabelapreco_desconto_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="comanda",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("mesa", "Por mesa"),
                    ("cliente", "Por cliente"),
                    ("individual", "Individual"),
                    ("compartilhada", "Compartilhada"),
                    ("qrcode", "QR Code"),
                ],
                default="mesa",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ComplementoItemComanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complementos",
                        to="food_service.itemcomanda",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complemento de item",
                "verbose_name_plural": "Complementos de item",
                "db_table": "food_service_complementos_item",
                "ordering": ["id"],
            },
        ),
    ]
