# Generated by Django 6.0.4 on 2026-08-06 20:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_service", "0004_mesa_qr_token"),
        ("produtos", "0030_itemtabelapreco_desconto_valor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nota", models.PositiveSmallIntegerField()),
                ("comentario", models.TextField(blank=True)),
                (
                    "comanda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="food_service.comanda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de atendimento",
                "verbose_name_plural": "Avaliações de atendimento",
                "db_table": "food_service_avaliacoes_atendimento",
            },
        ),
        migrations.CreateModel(
            name="ChamadoMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("garcom", "Chamar garçom"),
                            ("conta", "Pedir a conta"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("atendido", "Atendido")],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("atendido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "atendido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chamados",
                        to="food_service.mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado de mesa",
                "verbose_name_plural": "Chamados de mesa",
                "db_table": "food_service_chamados_mesa",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedidoPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=12
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "db_table": "food_service_itens_pedido_pendente",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ComplementoItemPedidoPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="produtos.produto",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complementos",
                        to="food_service.itempedidopendente",
                    ),
                ),
            ],
            options={
                "db_table": "food_service_complementos_pedido_pendente",
            },
        ),
        migrations.CreateModel(
            name="PedidoPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmado", "Confirmado"),
                            ("recusado", "Recusado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("recusado_motivo", models.CharField(blank=True, max_length=200)),
                (
                    "comanda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_pendentes",
                        to="food_service.comanda",
                    ),
                ),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos_pendentes",
                        to="food_service.mesa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido pendente",
                "verbose_name_plural": "Pedidos pendentes",
                "db_table": "food_service_pedidos_pendentes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="itempedidopendente",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="food_service.pedidopendente",
            ),
        ),
    ]
