# Generated by Django 6.0.4 on 2026-08-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_service",
            "0005_avaliacaoatendimento_chamadomesa_itempedidopendente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcomanda",
            name="entregue_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemcomanda",
            name="iniciado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemcomanda",
            name="prioridade",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="itemcomanda",
            name="pronto_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemcomanda",
            name="recebido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="itemcomanda",
            name="status_preparo",
            field=models.CharField(
                choices=[
                    ("recebido", "Recebido"),
                    ("em_preparo", "Em preparo"),
                    ("quase_pronto", "Quase pronto"),
                    ("pronto", "Pronto"),
                    ("entregue", "Entregue"),
                    ("cancelado", "Cancelado"),
                ],
                default="recebido",
                max_length=20,
            ),
        ),
    ]
