# Generated by Django 5.2.17 on 2026-09-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_parametrossistema_checkout_venda'),
        ('estoque', '0016_deposito_tipos_material'),
        ('produtos', '0031_produto_tempo_preparo_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaCoberturaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dias_critico', models.PositiveSmallIntegerField(default=3, help_text='Cobertura até este dia: Crítico')),
                ('dias_baixo', models.PositiveSmallIntegerField(default=7, help_text='Cobertura até este dia: Baixo')),
                ('dias_normal', models.PositiveSmallIntegerField(default=15, help_text='Cobertura até este dia: Normal')),
                ('dias_alto', models.PositiveSmallIntegerField(default=30, help_text='Cobertura até este dia: Alto; acima: Excesso')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faixas_cobertura_estoque', to='produtos.categoriaproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_cobertura_estoque', to='core.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faixas_cobertura_estoque', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Faixa de cobertura de estoque',
                'verbose_name_plural': 'Faixas de cobertura de estoque',
                'db_table': 'estoque_faixas_cobertura',
                'ordering': ['empresa_id', 'categoria_id', 'produto_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('categoria__isnull', True), ('produto__isnull', True)), fields=('empresa',), name='faixa_cobertura_padrao_unica_por_empresa'), models.UniqueConstraint(condition=models.Q(('produto__isnull', True)), fields=('empresa', 'categoria'), name='faixa_cobertura_unica_por_categoria'), models.UniqueConstraint(condition=models.Q(('produto__isnull', False)), fields=('empresa', 'produto'), name='faixa_cobertura_unica_por_produto')],
            },
        ),
    ]
