# Generated by Django 5.2.17 on 2026-09-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_parametrossistema_checkout_venda'),
        ('estoque', '0017_faixacoberturaestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAbcEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('A', 'A — maior giro'), ('B', 'B — giro intermediário'), ('C', 'C — menor giro')], max_length=1)),
                ('multiplicador_minimo', models.DecimalField(decimal_places=2, default=1, help_text='Multiplica o estoque mínimo cadastrado do produto (1 = sem alteração).', max_digits=5)),
                ('multiplicador_maximo', models.DecimalField(decimal_places=2, default=1, help_text='Multiplica o estoque máximo cadastrado do produto (1 = sem alteração).', max_digits=5)),
                ('dias_cobertura_extra', models.SmallIntegerField(default=0, help_text='Dias somados à meta de cobertura do equilíbrio (positivo = mais reserva, negativo = menos).')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_abc_estoque', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuração ABC de estoque',
                'verbose_name_plural': 'Configurações ABC de estoque',
                'db_table': 'estoque_configuracoes_abc',
                'ordering': ['empresa_id', 'classe'],
                'unique_together': {('empresa', 'classe')},
            },
        ),
    ]
