# Generated by Django 5.2.17 on 2026-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0018_configuracaoabcestoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenciatransferencia",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("sugerida", "Sugerida"),
                    ("aguardando_aprovacao", "Aguardando aprovação"),
                    ("aprovada", "Aprovada"),
                    ("separando", "Separando"),
                    ("expedida", "Expedida"),
                    ("em_transito", "Em trânsito"),
                    ("recebida", "Recebida"),
                    ("cancelada", "Cancelada"),
                ],
                db_index=True,
                default="aprovada",
                max_length=24,
            ),
        ),
    ]
