# Generated by Django 5.2.17 on 2026-09-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_parametrossistema_checkout_busca_nome_senha'),
        ('estoque', '0019_conferenciatransferencia_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoDemandaPonderada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_7_dias', models.PositiveSmallIntegerField(default=0)),
                ('peso_15_dias', models.PositiveSmallIntegerField(default=0)),
                ('peso_30_dias', models.PositiveSmallIntegerField(default=50)),
                ('peso_60_dias', models.PositiveSmallIntegerField(default=30)),
                ('peso_90_dias', models.PositiveSmallIntegerField(default=20)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_demanda_ponderada', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuração de demanda ponderada',
                'verbose_name_plural': 'Configurações de demanda ponderada',
                'db_table': 'estoque_configuracao_demanda_ponderada',
            },
        ),
    ]
