# Generated by Django 5.2.17 on 2026-09-14 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_perfilacesso_alcada_transferencia_and_more'),
        ('estoque', '0020_configuracaodemandaponderada'),
        ('produtos', '0031_produto_tempo_preparo_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAprovacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_nome', models.CharField(help_text='Ex.: Supervisor, Gerente, Diretor', max_length=60)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = sem teto (última faixa).', max_digits=12, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis_aprovacao_transferencia', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Nível de aprovação de transferência',
                'verbose_name_plural': 'Níveis de aprovação de transferência',
                'db_table': 'estoque_niveis_aprovacao_transferencia',
                'ordering': ['empresa_id', 'valor_minimo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], db_index=True, default='pendente', max_length=10)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_decisao', models.TextField(blank=True)),
                ('documento_numero', models.CharField(blank=True, help_text='Preenchido quando aprovada -- número da transferência real gerada.', max_length=20)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_transferencia_decididas', to=settings.AUTH_USER_MODEL)),
                ('filial_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_transferencia_destino', to='core.filial')),
                ('filial_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_transferencia_origem', to='core.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_transferencia', to='produtos.produto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_transferencia_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de transferência',
                'verbose_name_plural': 'Solicitações de transferência',
                'db_table': 'estoque_solicitacoes_transferencia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['filial_origem', 'status'], name='estoque_sol_filial__9cea81_idx')],
            },
        ),
        migrations.CreateModel(
            name='SugestaoEqualizacaoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade_sugerida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('score', models.PositiveSmallIntegerField()),
                ('destino_meta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_equalizacao', to='core.empresa')),
                ('filial_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.filial')),
                ('filial_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Snapshot de sugestão de equalização',
                'verbose_name_plural': 'Snapshots de sugestão de equalização',
                'db_table': 'estoque_snapshots_equalizacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'created_at'], name='estoque_sna_empresa_13a19d_idx'), models.Index(fields=['produto', 'filial_origem', 'filial_destino', 'created_at'], name='estoque_sna_produto_0bdc07_idx')],
            },
        ),
    ]
