# Generated by Django 5.2.17 on 2026-09-12 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0062_separacao_filial_segura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('prefixo', models.CharField(db_index=True, max_length=20)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('escopos', models.JSONField(default=list)),
                ('ips_permitidos', models.JSONField(blank=True, default=list, help_text='IPs ou redes CIDR. Em branco, permite qualquer origem.')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credenciais_integracao_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credenciais_integracao', to='core.empresa')),
                ('filiais', models.ManyToManyField(blank=True, help_text='Em branco, permite todas as filiais ativas da empresa.', related_name='credenciais_integracao', to='core.filial')),
            ],
            options={
                'verbose_name': 'Credencial de integração',
                'verbose_name_plural': 'Credenciais de integração',
                'db_table': 'integracoes_credenciais_api',
                'ordering': ['empresa__razao_social', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_integracao_nome_empresa')],
            },
        ),
    ]
