# Generated by Django 6.0.4 on 2026-07-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheGeocodificacao",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endereco_hash",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("endereco_consultado", models.CharField(max_length=300)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("precisao", models.CharField(blank=True, max_length=12)),
                ("provider", models.CharField(blank=True, max_length=30)),
                ("encontrado", models.BooleanField(default=True)),
                ("tentativas", models.PositiveSmallIntegerField(default=1)),
                ("erro", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "verbose_name": "Cache de geocodificação",
                "verbose_name_plural": "Cache de geocodificação",
                "db_table": "mapas_cache_geocodificacao",
                "indexes": [
                    models.Index(
                        fields=["encontrado", "tentativas"],
                        name="mapas_cache_encontr_20a6e1_idx",
                    )
                ],
            },
        ),
    ]
