# Generated by Django 6.0.4 on 2026-07-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_praca_territorio_rota_fks"),
        ("mapas", "0002_extensoes_e_indices_gist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteTerritorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territorios",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "praca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_territorio",
                        to="cadastros.praca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente por território",
                "verbose_name_plural": "Clientes por território",
                "db_table": "mapas_cliente_territorio",
                "indexes": [
                    models.Index(
                        fields=["praca"], name="mapas_clien_praca_i_2ec2c8_idx"
                    ),
                    models.Index(
                        fields=["cliente"], name="mapas_clien_cliente_32bdd6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("praca", "cliente"), name="uniq_cliente_por_praca"
                    )
                ],
            },
        ),
    ]
