# Generated by Django 6.0.4 on 2026-07-31 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_empresa_coordenadas"),
        ("mapas", "0003_cliente_territorio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroRota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paradas", models.PositiveSmallIntegerField(default=0)),
                ("distancia_m", models.PositiveIntegerField(default=0)),
                ("duracao_s", models.PositiveIntegerField(default=0)),
                ("otimizada", models.BooleanField(default=False)),
                (
                    "distancia_antes_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("duracao_antes_s", models.PositiveIntegerField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=30)),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotas_mapa",
                        to="core.filial",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mapas_registro_rota",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["filial", "-created_at"],
                        name="mapas_regis_filial__6f5cf1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SugestaoProximidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("venda_pdv_id", models.BigIntegerField(blank=True, null=True)),
                ("raio_m", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugestoes_mapa",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "db_table": "mapas_sugestao_proximidade",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["filial", "-created_at"],
                        name="mapas_suges_filial__e415e7_idx",
                    )
                ],
            },
        ),
    ]
