# Generated by Django 6.0.4 on 2026-08-02 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_vincular_rota_motorista_veiculo"),
        ("core", "0041_empresa_coordenadas"),
        ("mapas", "0004_registro_rota_e_sugestao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "raio_m",
                    models.PositiveIntegerField(
                        default=300, help_text="Raio da cerca em metros."
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geofences",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cerca virtual",
                "verbose_name_plural": "Cercas virtuais",
                "db_table": "mapas_geofence",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EventoGeofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                ("momento", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("distancia_m", models.PositiveIntegerField(default=0)),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_geofence",
                        to="cadastros.motorista",
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="mapas.geofence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de cerca",
                "verbose_name_plural": "Eventos de cerca",
                "db_table": "mapas_evento_geofence",
                "ordering": ["-momento"],
            },
        ),
        migrations.AddIndex(
            model_name="geofence",
            index=models.Index(
                fields=["filial", "ativo"], name="mapas_geofe_filial__f5e2d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventogeofence",
            index=models.Index(
                fields=["geofence", "motorista", "-momento"],
                name="mapas_event_geofenc_64ddff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventogeofence",
            index=models.Index(
                fields=["-momento"], name="mapas_event_momento_8a6b3e_idx"
            ),
        ),
    ]
