# Generated by Django 6.0.4 on 2026-08-02 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_vincular_rota_motorista_veiculo"),
        ("core", "0041_empresa_coordenadas"),
        ("mapas", "0005_geofence"),
        ("pdv", "0009_vendapdv_delivery_encerrado_em"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoPercurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("momento", models.DateTimeField()),
                ("velocidade_kmh", models.FloatField(blank=True, null=True)),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="percurso",
                        to="cadastros.motorista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto do percurso",
                "verbose_name_plural": "Pontos do percurso",
                "db_table": "mapas_ponto_percurso",
                "ordering": ["momento"],
                "indexes": [
                    models.Index(
                        fields=["motorista", "momento"],
                        name="mapas_ponto_motoris_a893cb_idx",
                    ),
                    models.Index(
                        fields=["filial", "momento"],
                        name="mapas_ponto_filial__52e8b7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PosicaoMotorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("momento", models.DateTimeField()),
                ("velocidade_kmh", models.FloatField(blank=True, null=True)),
                ("precisao_m", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "destino_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "destino_venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pdv.vendapdv",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posicoes_motorista",
                        to="core.filial",
                    ),
                ),
                (
                    "motorista",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posicao",
                        to="cadastros.motorista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posição do motorista",
                "verbose_name_plural": "Posições dos motoristas",
                "db_table": "mapas_posicao_motorista",
                "indexes": [
                    models.Index(
                        fields=["filial", "-momento"],
                        name="mapas_posic_filial__d516d1_idx",
                    )
                ],
            },
        ),
    ]
