# Generated by Django 5.2.17 on 2026-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapas", "0006_rastreio"),
    ]

    operations = [
        migrations.AddField(
            model_name="posicaomotorista",
            name="destinos_pendentes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
