# Generated by Django 6.0.4 on 2026-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0029_alter_atualizacaoprecoitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtabelapreco",
            name="desconto_valor",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Desconto máximo em R$ (valor), alternativo ao percentual.",
                max_digits=14,
            ),
        ),
    ]
