# Generated by Django 6.0.4 on 2026-08-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0030_itemtabelapreco_desconto_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="tempo_preparo_minutos",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
