# Generated by Django 6.0.4 on 2026-09-14 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0031_produto_tempo_preparo_minutos"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoApresentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "descricao",
                    models.CharField(
                        help_text="Ex: Unidade, Pacote 100, Caixa 1.000", max_length=60
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Codigo interno da apresentacao",
                        max_length=30,
                    ),
                ),
                (
                    "fator_conversao",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Quantidade de unidades base contida nesta apresentacao. Sempre absoluto, nunca encadeado.",
                        max_digits=14,
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Preco de venda proprio desta apresentacao (independente do preco_venda do produto).",
                        max_digits=14,
                    ),
                ),
                (
                    "padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Apresentacao usada por padrao na venda/PDV quando nenhuma outra for informada.",
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apresentacoes",
                        to="produtos.produto",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apresentacoes_produto",
                        to="produtos.unidademedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apresentacao de Produto",
                "verbose_name_plural": "Apresentacoes de Produto",
                "db_table": "produtos_apresentacoes",
                "ordering": ["produto", "fator_conversao"],
                "indexes": [
                    models.Index(
                        fields=["produto", "ativo"],
                        name="produtos_ap_produto_7c088d_idx",
                    )
                ],
                "unique_together": {("produto", "unidade", "descricao")},
            },
        ),
    ]
