# Generated by Django 6.0.4 on 2026-09-14 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0032_produto_apresentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtocodigobarras",
            name="apresentacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Apresentacao a que este EAN pertence. Opcional: nulo para codigos ainda nao migrados/vinculados.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codigos_barras",
                to="produtos.produtoapresentacao",
            ),
        ),
        migrations.AddIndex(
            model_name="produtocodigobarras",
            index=models.Index(
                fields=["apresentacao", "ativo"], name="pcb_apresentacao_ativo_idx"
            ),
        ),
    ]
