# Generated by Django 6.0.4 on 2026-09-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0033_codigobarras_apresentacao"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="produtoapresentacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("padrao", True)),
                fields=("produto",),
                name="uniq_produto_apresentacao_padrao",
            ),
        ),
    ]
