# Generated by Django 6.0.4 on 2026-09-14 02:43
#
# Substitui a flag unica `padrao` por duas flags independentes
# `principal_venda` e `principal_compra` (ver CLAUDE.md/discussao de
# modelagem). Ordem deliberada: adiciona os campos novos, copia o dado de
# `padrao` para ambos, so entao remove `padrao` e cria as constraints novas
# -- assim nenhuma apresentacao ja marcada como padrao perde a marcacao.

from django.db import migrations, models


def copiar_padrao_para_novas_flags(apps, schema_editor):
    ProdutoApresentacao = apps.get_model("produtos", "ProdutoApresentacao")
    ProdutoApresentacao.objects.filter(padrao=True).update(
        principal_venda=True, principal_compra=True,
    )


def copiar_novas_flags_para_padrao(apps, schema_editor):
    ProdutoApresentacao = apps.get_model("produtos", "ProdutoApresentacao")
    ProdutoApresentacao.objects.filter(
        models.Q(principal_venda=True) | models.Q(principal_compra=True),
    ).update(padrao=True)


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0034_apresentacao_padrao_unica"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="produtoapresentacao",
            name="uniq_produto_apresentacao_padrao",
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="principal_compra",
            field=models.BooleanField(
                default=False,
                help_text="Apresentacao usada por padrao na compra/entrada quando nenhuma outra for informada.",
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="principal_venda",
            field=models.BooleanField(
                default=False,
                help_text="Apresentacao usada por padrao na venda/PDV quando nenhuma outra for informada.",
            ),
        ),
        migrations.RunPython(
            copiar_padrao_para_novas_flags,
            reverse_code=copiar_novas_flags_para_padrao,
        ),
        migrations.AddConstraint(
            model_name="produtoapresentacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal_venda", True)),
                fields=("produto",),
                name="uniq_produto_apresentacao_principal_venda",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtoapresentacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal_compra", True)),
                fields=("produto",),
                name="uniq_produto_apresentacao_principal_compra",
            ),
        ),
        migrations.RemoveField(
            model_name="produtoapresentacao",
            name="padrao",
        ),
    ]
