# Generated by Django 5.2.17 on 2026-09-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0035_apresentacao_principal_venda_compra"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="produtoapresentacao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ativo", True)),
                fields=("produto", "unidade", "fator_conversao"),
                name="uniq_produto_apresentacao_ativa_unidade_fator",
                violation_error_message="Ja existe uma apresentacao ativa com a mesma unidade e fator de conversao para este produto.",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtoapresentacao",
            constraint=models.CheckConstraint(
                condition=models.Q(("fator_conversao__gt", 0)),
                name="chk_produto_apresentacao_fator_conversao_positivo",
                violation_error_message="O fator de conversao deve ser maior que zero.",
            ),
        ),
    ]
