# Generated by Django 5.2.17 on 2026-09-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0036_apresentacao_constraints_fator"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtoapresentacao",
            name="altura",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="largura",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="permite_compra",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="permite_estoque",
            field=models.BooleanField(
                default=True,
                help_text='Se desmarcado, esta apresentacao nao pode ser usada em movimentacao de estoque (ex: apresentacao so informativa, tipo "display com 6 caixas").',
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="permite_venda",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="peso_bruto",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="peso_liquido",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="preco_minimo",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Preco minimo de venda desta apresentacao. Vender abaixo exige override explicito.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="produtoapresentacao",
            name="profundidade",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
