# Generated by Django 5.2.17 on 2026-09-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0037_apresentacao_campos_fase8"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidademedida",
            name="casas_decimais",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Casas decimais aceitas na quantidade desta unidade ao arredondar (ver apps.produtos.services.conversao). Unidades de contagem (tipo=Unidade) normalmente usam 0.",
            ),
        ),
    ]
