# Generated by Django 5.2.17 on 2026-09-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_registroauditoria_modulo_produtos'),
        ('produtos', '0038_unidademedida_casas_decimais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoApresentacaoFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Apresentacao vinculada a filial',
                'verbose_name_plural': 'Apresentacoes vinculadas a filiais',
                'db_table': 'produtos_apresentacoes_filiais',
                'ordering': ['apresentacao', 'filial'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemtabelapreco',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemtabelapreco',
            name='apresentacao',
            field=models.ForeignKey(blank=True, help_text='Nulo = preco no nivel do produto (comportamento historico). Preenchido = preco especifico desta apresentacao nesta tabela (== nesta filial, via TabelaPrecoFilial), independente do preco_venda da apresentacao.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precos_tabela', to='produtos.produtoapresentacao'),
        ),
        migrations.AddConstraint(
            model_name='itemtabelapreco',
            constraint=models.UniqueConstraint(condition=models.Q(('apresentacao__isnull', True)), fields=('tabela', 'produto', 'quantidade_minima'), name='uniq_item_tabela_preco_sem_apresentacao'),
        ),
        migrations.AddConstraint(
            model_name='itemtabelapreco',
            constraint=models.UniqueConstraint(condition=models.Q(('apresentacao__isnull', False)), fields=('tabela', 'produto', 'apresentacao', 'quantidade_minima'), name='uniq_item_tabela_preco_com_apresentacao'),
        ),
        migrations.AddField(
            model_name='produtoapresentacaofilial',
            name='apresentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais_vinculo', to='produtos.produtoapresentacao'),
        ),
        migrations.AddField(
            model_name='produtoapresentacaofilial',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apresentacoes_vinculadas', to='core.filial'),
        ),
        migrations.AddIndex(
            model_name='produtoapresentacaofilial',
            index=models.Index(fields=['filial', 'ativo'], name='produtos_ap_filial__233a12_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoapresentacaofilial',
            index=models.Index(fields=['apresentacao', 'ativo'], name='produtos_ap_apresen_b69fb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtoapresentacaofilial',
            unique_together={('apresentacao', 'filial')},
        ),
    ]
