# Generated by Django 5.2.17 on 2026-10-01 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0040_produto_balanca_mgv7'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='agendavel',
            field=models.BooleanField(db_index=True, default=False, help_text='Permite oferecer este serviço na agenda e nos canais de atendimento.', verbose_name='Disponível para agendamento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='duracao_servico_minutos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tempo que o serviço ocupa na agenda.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Duração do serviço (min)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='intervalo_apos_servico_minutos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tempo de limpeza, preparo ou descanso antes do próximo atendimento.', validators=[django.core.validators.MaxValueValidator(1440)], verbose_name='Intervalo após o serviço (min)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(choices=[('unitario', 'Unidade'), ('fracionado', 'Fracionado'), ('granel_peso', 'Granel (peso)'), ('granel_volume', 'Granel (volume)'), ('granel_metragem', 'Granel (metragem)'), ('servico', 'Serviço'), ('kit', 'Kit')], default='unitario', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('agendavel', False), ('tipo_produto', 'servico'), _connector='OR'), name='produto_agendavel_apenas_servico'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('agendavel', False), ('duracao_servico_minutos__gt', 0), _connector='OR'), name='produto_agendavel_com_duracao'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_servico_minutos__isnull', True), ('duracao_servico_minutos__lte', 1440), _connector='OR'), name='produto_duracao_servico_max_1440'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('intervalo_apos_servico_minutos__lte', 1440)), name='produto_intervalo_servico_max_1440'),
        ),
    ]
