# Generated by Django 5.2.17 on 2026-08-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_food_service_so_padaria"),
        ("fiscal", "0007_aliquota_ibpt"),
        ("produtos", "0031_produto_tempo_preparo_minutos"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaturezaOperacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "codigo",
                    models.SlugField(
                        help_text="Identificador curto usado nas telas e nos relatórios.",
                        max_length=40,
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text='O texto que vai no campo "natureza da operação" da nota.',
                        max_length=120,
                    ),
                ),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("venda", "Venda"),
                            (
                                "remessa_venda_fora",
                                "Remessa para venda fora do estabelecimento",
                            ),
                            ("venda_fora", "Venda fora do estabelecimento"),
                            (
                                "retorno_venda_fora",
                                "Retorno de venda fora do estabelecimento",
                            ),
                            ("bonificacao", "Bonificação"),
                            ("remessa_simples", "Outra remessa"),
                            ("retorno_simples", "Outro retorno"),
                        ],
                        db_index=True,
                        help_text="O comportamento que o sistema executa nesta operação.",
                        max_length=30,
                    ),
                ),
                (
                    "movimenta_estoque",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque para operações que só geram documento.",
                    ),
                ),
                (
                    "tipo_operacao_estoque",
                    models.CharField(
                        blank=True,
                        help_text="Tipo da movimentação de estoque (ver MovimentacaoEstoque). Em branco, o sistema usa o padrão da espécie.",
                        max_length=30,
                    ),
                ),
                (
                    "gera_financeiro",
                    models.BooleanField(
                        default=True,
                        help_text="Bonificação e remessa normalmente não geram contas a receber. Desmarque quando a operação não cobra do destinatário.",
                    ),
                ),
                (
                    "exige_destinatario",
                    models.BooleanField(
                        default=True,
                        help_text="A remessa para venda fora sai sem comprador — a nota é contra a própria empresa. Desmarque nesses casos.",
                    ),
                ),
                (
                    "entra_no_mdfe",
                    models.BooleanField(
                        default=True,
                        help_text="Se a nota desta operação deve constar no MDF-e da viagem.",
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natureza de operação",
                "verbose_name_plural": "Naturezas de operação",
                "db_table": "fiscal_naturezas_operacao",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="RegraNaturezaOperacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uf_origem",
                    models.CharField(blank=True, db_index=True, max_length=2),
                ),
                (
                    "uf_destino",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Deixe vazio e marque "somente interestadual" para a regra de fora do estado.',
                        max_length=2,
                    ),
                ),
                (
                    "somente_interestadual",
                    models.BooleanField(
                        default=False,
                        help_text="Vale quando origem e destino são UFs diferentes, qualquer que seja o destino.",
                    ),
                ),
                (
                    "regime_tributario",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("ncm", models.CharField(blank=True, db_index=True, max_length=8)),
                ("cfop", models.CharField(max_length=5)),
                ("cst_icms", models.CharField(blank=True, max_length=3)),
                ("csosn", models.CharField(blank=True, max_length=3)),
                ("cst_pis", models.CharField(blank=True, max_length=2)),
                ("cst_cofins", models.CharField(blank=True, max_length=2)),
                ("cst_ipi", models.CharField(blank=True, max_length=2)),
                (
                    "aliquota_icms",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "reducao_base_icms",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "finalidade_nfe",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 normal, 2 complementar, 3 ajuste, 4 devolução.",
                    ),
                ),
                (
                    "natureza_operacao_texto",
                    models.CharField(
                        blank=True,
                        help_text="Sobrescreve o texto da natureza, quando esta regra pede outro.",
                        max_length=120,
                    ),
                ),
                (
                    "informacoes_complementares",
                    models.TextField(
                        blank=True,
                        help_text="Vai para o campo de informações adicionais da nota.",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "vigencia_fim",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "natureza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras",
                        to="fiscal.naturezaoperacao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_natureza",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra de natureza de operação",
                "verbose_name_plural": "Regras de natureza de operação",
                "db_table": "fiscal_regras_natureza_operacao",
                "ordering": ["natureza", "-vigencia_inicio", "uf_destino"],
            },
        ),
        migrations.AddIndex(
            model_name="naturezaoperacao",
            index=models.Index(
                fields=["filial", "especie", "ativo"],
                name="fiscal_natu_filial__c19800_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="naturezaoperacao",
            constraint=models.UniqueConstraint(
                fields=("filial", "codigo"), name="natureza_operacao_codigo_por_filial"
            ),
        ),
        migrations.AddIndex(
            model_name="regranaturezaoperacao",
            index=models.Index(
                fields=["natureza", "ativo"], name="fiscal_regr_naturez_f9ce96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regranaturezaoperacao",
            index=models.Index(
                fields=["natureza", "uf_destino", "ativo"],
                name="fiscal_regr_naturez_e583cf_idx",
            ),
        ),
    ]
