# Generated by Django 5.2.17 on 2026-08-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0008_naturezas_de_operacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="regranaturezaoperacao",
            name="aliquota_cofins",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="regranaturezaoperacao",
            name="aliquota_ipi",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="regranaturezaoperacao",
            name="aliquota_pis",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=7, null=True
            ),
        ),
    ]
