# Generated by Django 5.2.17 on 2026-10-08 19:46

import django.db.models.deletion
from django.db import migrations, models


def mover_prontos_para_pendencia(apps, schema_editor):
    PedidoCatalogo = apps.get_model('catalogo', 'PedidoCatalogo')
    PedidoCatalogo.objects.using(schema_editor.connection.alias).filter(
        status='pronto',
    ).update(status='pendente_caixa')


def restaurar_prontos(apps, schema_editor):
    PedidoCatalogo = apps.get_model('catalogo', 'PedidoCatalogo')
    PedidoCatalogo.objects.using(schema_editor.connection.alias).filter(
        status='pendente_caixa',
    ).update(status='pronto')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pdv', '0035_rotadelivery_conclusoes_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocatalogo',
            name='venda_pdv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_catalogo', to='pdv.vendapdv'),
        ),
        migrations.AlterField(
            model_name='pedidocatalogo',
            name='status',
            field=models.CharField(choices=[('aguardando_cliente', 'Aguardando confirmação do cliente'), ('aguardando_loja', 'Aguardando aprovação da loja'), ('aprovado', 'Aprovado'), ('em_separacao', 'Em separação'), ('pendente_caixa', 'Pendente no caixa'), ('pago', 'Pagamento confirmado'), ('pronto', 'Pronto para entrega'), ('saiu_entrega', 'Saiu para entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando_cliente', max_length=28),
        ),
        migrations.RunPython(mover_prontos_para_pendencia, restaurar_prontos),
    ]
