# Generated by Django 5.2.17 on 2026-09-13 17:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_analise_custo_compra'),
        ('compras', '0018_entradanf_deposito'),
        ('core', '0063_analise_custo_compra'),
        ('produtos', '0031_produto_tempo_preparo_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoTributarioCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_bruto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('custos_nao_recuperaveis', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('credito_ibs', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('credito_cbs', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('outros_creditos', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('credito_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('custo_efetivo', models.DecimalField(decimal_places=4, max_digits=18)),
                ('regra_snapshot', models.JSONField(blank=True, default=dict)),
                ('vencedor', models.BooleanField(db_index=True, default=False)),
                ('posicao', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'calculos_tributarios_compra',
                'ordering': ['posicao', 'custo_efetivo'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=24)),
                ('data_referencia', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('analisada', 'Analisada')], default='analisada', max_length=16)),
                ('visao_padrao', models.CharField(choices=[('menor_preco', 'Menor preco nominal'), ('maior_credito', 'Maior credito tributario'), ('menor_custo', 'Menor custo efetivo')], default='menor_custo', max_length=20)),
                ('regime_comprador', models.CharField(choices=[('mei', 'MEI'), ('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=20)),
                ('regime_ibs_cbs_comprador', models.CharField(choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], max_length=10)),
                ('empresa_snapshot', models.JSONField(default=dict)),
                ('valor_nominal_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('creditos_estimados_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('custo_efetivo_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('economia_estimada', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fornecedor_base_nome', models.CharField(blank=True, max_length=150)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cotacao de compra',
                'verbose_name_plural': 'Cotacoes de compra',
                'db_table': 'cotacoes_compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_supplier', models.BooleanField(default=False)),
                ('supplier_name', models.CharField(max_length=150)),
                ('supplier_cnpj', models.CharField(blank=True, max_length=14)),
                ('supplier_tax_regime', models.CharField(choices=[('mei', 'MEI'), ('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=20)),
                ('supplier_tax_ibs_cbs', models.CharField(choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], max_length=10)),
                ('supplier_snapshot', models.JSONField(blank=True, default=dict)),
                ('salvo_no_cadastro', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cotacoes_compra_fornecedores',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto_descricao', models.CharField(max_length=150)),
                ('produto_codigo', models.CharField(blank=True, max_length=30)),
                ('produto_ncm', models.CharField(blank=True, max_length=8)),
                ('produto_fiscal_snapshot', models.JSONField(blank=True, default=dict)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidade_sigla', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'db_table': 'cotacoes_compra_itens',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoCompraPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('frete_nao_recuperavel', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('condicoes_comerciais', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cotacoes_compra_precos',
            },
        ),
        migrations.CreateModel(
            name='RegraTributariaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('data_inicial', models.DateField(db_index=True)),
                ('data_final', models.DateField(blank=True, db_index=True, null=True)),
                ('regime_comprador', models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=20)),
                ('regime_fornecedor', models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=20)),
                ('regime_ibs_cbs_comprador', models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], max_length=10)),
                ('regime_ibs_cbs_fornecedor', models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], max_length=10)),
                ('ncm_prefixo', models.CharField(blank=True, help_text='Opcional. Quanto maior o prefixo, mais especifica e a regra.', max_length=8)),
                ('percentual_credito_ibs', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percentual_credito_cbs', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percentual_outros_creditos', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('condicoes', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Regra tributaria de compra',
                'verbose_name_plural': 'Regras tributarias de compra',
                'db_table': 'regras_tributarias_compra',
                'ordering': ['-data_inicial', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='cotacaocompra',
            name='filial',
            field=models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial'),
        ),
        migrations.AddField(
            model_name='cotacaocompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotacaocomprafornecedor',
            name='cotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='compras.cotacaocompra'),
        ),
        migrations.AddField(
            model_name='cotacaocomprafornecedor',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_cotacao', to='cadastros.fornecedor'),
        ),
        migrations.AddField(
            model_name='cotacaocompraitem',
            name='cotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.cotacaocompra'),
        ),
        migrations.AddField(
            model_name='cotacaocompraitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotacoes_compra', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='cotacaocomprapreco',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='compras.cotacaocomprafornecedor'),
        ),
        migrations.AddField(
            model_name='cotacaocomprapreco',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos', to='compras.cotacaocompraitem'),
        ),
        migrations.AddField(
            model_name='calculotributariocompra',
            name='preco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo', to='compras.cotacaocomprapreco'),
        ),
        migrations.AddField(
            model_name='regratributariacompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_tributarias_compra', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='regratributariacompra',
            name='classe_fiscal',
            field=models.ForeignKey(blank=True, help_text='Opcional. Reutiliza a classificacao fiscal ja vinculada ao produto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_credito_compra', to='produtos.classefiscal'),
        ),
        migrations.AddField(
            model_name='calculotributariocompra',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculos', to='compras.regratributariacompra'),
        ),
        migrations.AddIndex(
            model_name='cotacaocompra',
            index=models.Index(fields=['filial', '-created_at'], name='cotacoes_co_filial__09b0a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotacaocompraitem',
            unique_together={('cotacao', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='cotacaocomprapreco',
            unique_together={('item', 'fornecedor')},
        ),
        migrations.AddIndex(
            model_name='regratributariacompra',
            index=models.Index(fields=['empresa', 'ativo', 'data_inicial'], name='regras_trib_empresa_4f0aad_idx'),
        ),
    ]
