# Generated by Django 5.2.16 on 2026-07-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_praca_rota'),
        ('produtos', '0030_itemtabelapreco_desconto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tabela_preco',
            field=models.ForeignKey(blank=True, help_text='Quando vazia, usa o preco padrao cadastrado no produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='produtos.tabelapreco'),
        ),
    ]
