# Generated by Django 6.0.4 on 2026-07-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0012_coordenadas_geo"),
    ]

    operations = [
        migrations.AddField(
            model_name="praca",
            name="bbox_leste",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="praca",
            name="bbox_norte",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="praca",
            name="bbox_oeste",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="praca",
            name="bbox_sul",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="praca",
            name="cor",
            field=models.CharField(
                default="#3b82f6",
                help_text="Cor do território no mapa (hex).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="praca",
            name="meta_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Meta de faturamento do território, para o comparativo meta x realizado.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="praca",
            name="poligono",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="praca",
            name="representante",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsável comercial pelo território",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pracas",
                to="cadastros.representante",
            ),
        ),
        migrations.AddField(
            model_name="praca",
            name="supervisor",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="rota",
            name="motorista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rotas",
                to="cadastros.motorista",
                verbose_name="Motorista padrão",
            ),
        ),
        migrations.AddField(
            model_name="rota",
            name="veiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rotas",
                to="cadastros.veiculo",
                verbose_name="Veículo padrão",
            ),
        ),
        migrations.AlterField(
            model_name="rota",
            name="motorista_padrao",
            field=models.CharField(
                blank=True,
                help_text="LEGADO: preencha o campo Motorista. Mantido para registros sem cadastro.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rota",
            name="veiculo_padrao",
            field=models.CharField(
                blank=True,
                help_text="LEGADO: preencha o campo Veículo. Mantido para registros sem cadastro.",
                max_length=20,
            ),
        ),
    ]
