# Generated by Django 5.2.17 on 2026-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='regime_ibs_cbs',
            field=models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('regular', 'Regime regular')], help_text='Apuracao de IBS/CBS do fornecedor.', max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('mei', 'MEI'), ('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], help_text='Usado em calculos fiscais e pode ser informado apenas na cotacao.', max_length=20),
        ),
    ]
