# Generated by Django 6.0.4 on 2026-07-26 17:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0010_praca_rota'),
        ('core', '0031_alter_parametrossistema_certificado_base64_and_more'),
        ('pdv', '0007_vendapdv_observacao'),
        ('produtos', '0030_itemtabelapreco_desconto_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo_pendente', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo_expirado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo_utilizado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo_cancelado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo_total_gerado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carteiras_cashback', to='cadastros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras_cashback', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Carteira de Cashback',
                'verbose_name_plural': 'Carteiras de Cashback',
                'db_table': 'cashback_carteira',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentual_global', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de cashback aplicado quando nenhuma regra mais específica existir.', max_digits=5)),
                ('valor_minimo_gerar', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo da compra para gerar cashback.', max_digits=14)),
                ('valor_minimo_usar', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo da compra para permitir uso de cashback como pagamento.', max_digits=14)),
                ('percentual_maximo_uso_venda', models.DecimalField(decimal_places=2, default=100, help_text='Percentual máximo do total da venda que pode ser pago com cashback.', max_digits=5)),
                ('dias_validade', models.PositiveIntegerField(default=90, help_text='Dias até o crédito de cashback expirar.')),
                ('modo_estorno_usado', models.CharField(choices=[('negativo', 'Permitir saldo negativo na carteira'), ('conta_a_receber', 'Gerar conta a receber do cliente')], default='conta_a_receber', help_text='O que fazer quando uma venda cancelada já teve seu cashback gasto pelo cliente.', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_cashback', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Deixe em branco para configuração padrão da empresa (fallback global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_cashback', to='core.filial')),
            ],
            options={
                'verbose_name': 'Configuração de Cashback',
                'verbose_name_plural': 'Configurações de Cashback',
                'db_table': 'cashback_configuracao',
            },
        ),
        migrations.CreateModel(
            name='MovimentoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('credito_venda', 'Crédito por venda'), ('debito_utilizacao', 'Débito por utilização'), ('estorno', 'Estorno'), ('cancelamento', 'Cancelamento'), ('expiracao', 'Expiração'), ('ajuste_manual', 'Ajuste manual')], db_index=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Sempre positivo; a direção é definida pelo tipo.', max_digits=14)),
                ('saldo_apos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('data_validade', models.DateField(blank=True, help_text='Só preenchido em créditos por venda — data em que este crédito expira.', null=True)),
                ('observacao', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('pdv', 'PDV'), ('manual', 'Manual'), ('sistema', 'Sistema'), ('api', 'API')], default='sistema', max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255)),
                ('chave_idempotencia', models.CharField(blank=True, help_text="Chave única para impedir duplicidade (ex.: 'venda:123:credito').", max_length=100, null=True, unique=True)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='cashback.carteiracashback')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_cashback', to='cadastros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_cashback', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_cashback', to='core.filial')),
                ('item_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_cashback', to='pdv.itemvendapdv')),
                ('usuario', models.ForeignKey(blank=True, help_text='Operador responsável pelo lançamento (venda, ajuste manual, etc).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_cashback', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_cashback', to='pdv.vendapdv')),
            ],
            options={
                'verbose_name': 'Movimento de Cashback',
                'verbose_name_plural': 'Movimentos de Cashback',
                'db_table': 'cashback_movimento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegraCashbackCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_minimo_gerar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gera_cashback', models.BooleanField(default=True, help_text='Desmarque para excluir toda a categoria do cashback.')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_cashback', to='produtos.categoriaproduto')),
            ],
            options={
                'verbose_name': 'Regra de Cashback por Categoria',
                'verbose_name_plural': 'Regras de Cashback por Categoria',
                'db_table': 'cashback_regra_categoria',
            },
        ),
        migrations.CreateModel(
            name='RegraCashbackEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_minimo_gerar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_cashback', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Regra de Cashback por Empresa',
                'verbose_name_plural': 'Regras de Cashback por Empresa',
                'db_table': 'cashback_regra_empresa',
            },
        ),
        migrations.CreateModel(
            name='RegraCashbackFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_minimo_gerar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_cashback', to='core.filial')),
            ],
            options={
                'verbose_name': 'Regra de Cashback por Filial',
                'verbose_name_plural': 'Regras de Cashback por Filial',
                'db_table': 'cashback_regra_filial',
            },
        ),
        migrations.CreateModel(
            name='RegraCashbackProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_minimo_gerar', models.DecimalField(blank=True, decimal_places=2, help_text='Substitui o mínimo padrão da configuração, se informado.', max_digits=14, null=True)),
                ('gera_cashback', models.BooleanField(default=True, help_text='Desmarque para excluir este produto do cashback, mesmo com percentual configurado.')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_cashback', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Regra de Cashback por Produto',
                'verbose_name_plural': 'Regras de Cashback por Produto',
                'db_table': 'cashback_regra_produto',
            },
        ),
        migrations.CreateModel(
            name='CampanhaCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('prioridade', models.PositiveIntegerField(default=0, help_text='Quando mais de uma campanha se aplica no mesmo dia, vence a de maior prioridade.')),
                ('dias_semana', models.JSONField(blank=True, default=list, help_text='Lista de dias da semana em que a campanha vale (0=segunda … 6=domingo). Vazio = todos os dias.')),
                ('categorias', models.ManyToManyField(blank=True, help_text='Restringe a campanha a categorias específicas. Vazio = todas as categorias.', related_name='campanhas_cashback', to='produtos.categoriaproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_cashback', to='core.empresa')),
                ('filiais', models.ManyToManyField(blank=True, help_text='Restringe a campanha a filiais específicas. Vazio = todas as filiais da empresa.', related_name='campanhas_cashback', to='core.filial')),
                ('produtos', models.ManyToManyField(blank=True, help_text='Restringe a campanha a produtos específicos. Vazio = todos os produtos elegíveis.', related_name='campanhas_cashback', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Campanha de Cashback',
                'verbose_name_plural': 'Campanhas de Cashback',
                'db_table': 'cashback_campanha',
                'ordering': ['-prioridade', '-data_inicio'],
                'indexes': [models.Index(fields=['empresa', 'ativo', 'data_inicio', 'data_fim'], name='cashback_ca_empresa_98d1c4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='carteiracashback',
            index=models.Index(fields=['empresa', 'cliente'], name='cashback_ca_empresa_8a946a_idx'),
        ),
        migrations.AddConstraint(
            model_name='carteiracashback',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente'), name='uniq_carteira_cashback_empresa_cliente'),
        ),
        migrations.AddConstraint(
            model_name='configuracaocashback',
            constraint=models.UniqueConstraint(fields=('empresa', 'filial'), name='uniq_configuracao_cashback_empresa_filial'),
        ),
        migrations.AddIndex(
            model_name='movimentocashback',
            index=models.Index(fields=['carteira', '-created_at'], name='cashback_mo_carteir_2c2610_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocashback',
            index=models.Index(fields=['cliente', '-created_at'], name='cashback_mo_cliente_5fd1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocashback',
            index=models.Index(fields=['tipo', 'data_validade'], name='cashback_mo_tipo_18cb01_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocashback',
            index=models.Index(fields=['venda'], name='cashback_mo_venda_i_aa656c_idx'),
        ),
    ]
