from django.urls import path

from apps.logistica import views, views_viagem

app_name = "logistica"

urlpatterns = [
    path("", views.RomaneioCargaListView.as_view(), name="romaneio-list"),
    path("romaneios/", views.RomaneioCargaListView.as_view(), name="romaneio-list"),
    path("romaneios/novo/", views.RomaneioCargaCreateView.as_view(), name="romaneio-create"),
    path("romaneios/<int:pk>/", views.RomaneioCargaDetailView.as_view(), name="romaneio-detail"),
    path("romaneios/<int:pk>/editar/", views.RomaneioCargaUpdateView.as_view(), name="romaneio-update"),
    path("romaneios/<int:pk>/alterar-status/", views.RomaneioAlterarStatusView.as_view(), name="romaneio-alterar-status"),
    path("romaneios/<int:pk>/itens/novo/", views.ItemRomaneioCreateView.as_view(), name="romaneio-item-create"),
    path("romaneios/<int:pk>/itens/<int:item_pk>/remover/", views.ItemRomaneioDeleteView.as_view(), name="romaneio-item-delete"),
    path("ordens-coleta/", views.OrdemColetaListView.as_view(), name="ordem-coleta-list"),
    path("ordens-coleta/nova/", views.OrdemColetaCreateView.as_view(), name="ordem-coleta-create"),
    path("ordens-coleta/<int:pk>/", views.OrdemColetaDetailView.as_view(), name="ordem-coleta-detail"),
    path("ordens-coleta/<int:pk>/editar/", views.OrdemColetaUpdateView.as_view(), name="ordem-coleta-update"),
    path("ordens-coleta/<int:pk>/itens/novo/", views.ItemOrdemColetaCreateView.as_view(), name="ordem-coleta-item-create"),
    path("ordens-coleta/<int:pk>/itens/<int:item_pk>/remover/", views.ItemOrdemColetaDeleteView.as_view(), name="ordem-coleta-item-delete"),
    # ── Viagem e carga ───────────────────────────────────────────────
    path("viagens/", views_viagem.ViagemListView.as_view(), name="viagem-list"),
    path("viagens/nova/", views_viagem.ViagemCreateView.as_view(), name="viagem-create"),
    path("viagens/<int:pk>/", views_viagem.ViagemDetailView.as_view(), name="viagem-detail"),
    path("viagens/<int:pk>/editar/", views_viagem.ViagemUpdateView.as_view(), name="viagem-update"),
    path("viagens/<int:pk>/status/", views_viagem.ViagemMudarStatusView.as_view(), name="viagem-status"),
    path("viagens/<int:pk>/fechar-carga/", views_viagem.ViagemFecharCargaView.as_view(), name="viagem-fechar-carga"),
    path("viagens/<int:pk>/cancelar/", views_viagem.ViagemCancelarView.as_view(), name="viagem-cancelar"),
    path("viagens/<int:pk>/vendas/", views_viagem.ViagemVendasView.as_view(), name="viagem-vendas"),
    path("viagens/<int:pk>/tratamento-fiscal/", views_viagem.ViagemTratamentoFiscalJsonView.as_view(), name="viagem-tratamento-fiscal"),
    path("viagens/<int:pk>/carga/<str:especie>/", views_viagem.ViagemItemCreateView.as_view(), name="viagem-item-create"),
    path("viagens/<int:pk>/carga/item/<int:item_pk>/remover/", views_viagem.ViagemItemDeleteView.as_view(), name="viagem-item-delete"),

    path("manifestos/", views.ManifestoCargaListView.as_view(), name="manifesto-list"),
    path("manifestos/novo/", views.ManifestoCargaCreateView.as_view(), name="manifesto-create"),
    path("manifestos/<int:pk>/", views.ManifestoCargaDetailView.as_view(), name="manifesto-detail"),
    path("manifestos/<int:pk>/editar/", views.ManifestoCargaUpdateView.as_view(), name="manifesto-update"),
    path("manifestos/<int:pk>/documentos/novo/", views.DocumentoManifestoCreateView.as_view(), name="manifesto-documento-create"),
    path("manifestos/<int:pk>/documentos/<int:documento_pk>/remover/", views.DocumentoManifestoDeleteView.as_view(), name="manifesto-documento-delete"),
    path("cte/", views.CTeListView.as_view(), name="cte-list"),
    path("cte/novo/", views.CTeCreateView.as_view(), name="cte-create"),
    path("cte/<int:pk>/", views.CTeDetailView.as_view(), name="cte-detail"),
    path("cte/<int:pk>/editar/", views.CTeUpdateView.as_view(), name="cte-update"),
    path("cte/<int:pk>/documentos/novo/", views.DocumentoCTeCreateView.as_view(), name="cte-documento-create"),
    path("cte/<int:pk>/documentos/<int:documento_pk>/remover/", views.DocumentoCTeDeleteView.as_view(), name="cte-documento-delete"),
    path("cte/<int:pk>/emitir/", views.CTeEmitirView.as_view(), name="cte-emitir"),
    path("cte/<int:pk>/consultar/", views.CTeConsultarView.as_view(), name="cte-consultar"),
    path("cte/<int:pk>/cancelar/", views.CteCancelarView.as_view(), name="cte-cancelar"),
    path("cte/<int:pk>/dacte/", views.CteDACTEView.as_view(), name="cte-dacte"),
    # OMS — Pedidos de Expedição
    path("pedidos/", views.PedidoExpedicaoListView.as_view(), name="pedido-expedicao-list"),
    path("pedidos/novo/", views.PedidoExpedicaoCreateView.as_view(), name="pedido-expedicao-create"),
    path("pedidos/<int:pk>/", views.PedidoExpedicaoDetailView.as_view(), name="pedido-expedicao-detail"),
    path("pedidos/<int:pk>/editar/", views.PedidoExpedicaoUpdateView.as_view(), name="pedido-expedicao-update"),
    path("pedidos/<int:pk>/excluir/", views.PedidoExpedicaoDeleteView.as_view(), name="pedido-expedicao-delete"),
    path("pedidos/<int:pk>/cancelar/", views.PedidoExpedicaoCancelarView.as_view(), name="pedido-expedicao-cancelar"),
    path("pedidos/<int:pk>/itens/novo/", views.ItemPedidoExpedicaoCreateView.as_view(), name="pedido-expedicao-item-create"),
    path("pedidos/<int:pk>/itens/<int:item_pk>/remover/", views.ItemPedidoExpedicaoDeleteView.as_view(), name="pedido-expedicao-item-delete"),
    path("pedidos/<int:pk>/itens/<int:item_pk>/toggle-status/", views.ItemPedidoExpedicaoToggleStatusView.as_view(), name="pedido-expedicao-item-toggle"),
    # MDF-e
    path("mdfe/", views.MDFeListView.as_view(), name="mdfe-list"),
    path("mdfe/novo/", views.MDFeCreateView.as_view(), name="mdfe-create"),
    path("mdfe/buscar-nfe/", views.MDFeNFeSearchView.as_view(), name="mdfe-buscar-nfe"),
    path("mdfe/<int:pk>/", views.MDFeDetailView.as_view(), name="mdfe-detail"),
    path("mdfe/<int:pk>/editar/", views.MDFeUpdateView.as_view(), name="mdfe-update"),
    path("mdfe/<int:pk>/vincular-nfe/", views.MDFeVincularNFeView.as_view(), name="mdfe-vincular-nfe"),
    path("mdfe/<int:pk>/vincular-documentos/", views.MDFeVincularDocumentosView.as_view(), name="mdfe-vincular-documentos"),
    path("mdfe/<int:pk>/alterar-status/", views.MDFeAlterarStatusView.as_view(), name="mdfe-alterar-status"),
    path("mdfe/<int:pk>/emitir/", views.MDFeEmitirView.as_view(), name="mdfe-emitir"),
    path("mdfe/<int:pk>/consultar/", views.MDFeConsultarView.as_view(), name="mdfe-consultar"),
    path("mdfe/<int:pk>/cancelar-focus/", views.MDFeCancelarFocusView.as_view(), name="mdfe-cancelar-focus"),
    path("mdfe/<int:pk>/encerrar/", views.MDFeEncerrarView.as_view(), name="mdfe-encerrar"),
    path("mdfe/<int:pk>/damdfe/", views.MDFeDamdfeView.as_view(), name="mdfe-damdfe"),
    path("mdfe/<int:pk>/documentos/novo/", views.DocumentoMDFeCreateView.as_view(), name="mdfe-documento-create"),
    path("mdfe/<int:pk>/documentos/<int:documento_pk>/remover/", views.DocumentoMDFeDeleteView.as_view(), name="mdfe-documento-delete"),
]
