# Generated by Django 6.0.4 on 2026-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0006_vendapdv_sessao_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendapdv",
            name="observacao",
            field=models.TextField(
                blank=True,
                help_text="Observação geral da venda (ex.: entregar após meio-dia).",
            ),
        ),
    ]
