# Generated by Django 6.0.4 on 2026-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0009_vendapdv_delivery_encerrado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendapdv",
            name="pagamentos_rascunho",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
