# Generated by Django 5.2.17 on 2026-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0011_pagamentovendapdv_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='taxa_calculada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='taxa_fixa_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='taxa_percentual_aplicada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='valor_taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
