# Generated by Django 5.2.17 on 2026-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0012_pagamentovendapdv_taxa_calculada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='data_liquidacao_prevista',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentovendapdv',
            name='prazo_compensacao_aplicado',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
