# Generated by Django 6.0.4 on 2026-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0018_vendapdv_cancelamento_autorizado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendapdv",
            name="bonificacao",
            field=models.BooleanField(default=False),
        ),
    ]
