# Generated by Django 5.2.17 on 2026-09-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0022_dados_teste_equilibrio_ited"),
        ("produtos", "0039_apresentacao_filial_e_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvendapdv",
            name="apresentacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_venda_pdv",
                to="produtos.produtoapresentacao",
            ),
        ),
        migrations.AddField(
            model_name="itemvendapdv",
            name="apresentacao_fator_conversao",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Fator de conversao da apresentacao NO MOMENTO da venda -- nao o atual.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemvendapdv",
            name="quantidade_comercial",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Quantidade na unidade da apresentacao (ex: 2 caixas). `quantidade` continua sendo a mesma coisa convertida pra unidade base.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
