# Generated by Django 5.2.17 on 2026-09-18 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0026_auditoria_e_testes_contingencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacaopdvoffline',
            name='armazenamento_persistente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacaopdvoffline',
            name='armazenamento_quota',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacaopdvoffline',
            name='armazenamento_uso',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instalacaopdvoffline',
            name='pwa_instalado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OcorrenciaPDVOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_tratamento', 'Em tratamento'), ('resolvida', 'Resolvida')], db_index=True, default='aberta', max_length=20)),
                ('status_fila', models.CharField(default='pendente', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('detectada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('vista_por_ultimo_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('responsavel_id', models.BigIntegerField(blank=True, null=True)),
                ('responsavel_nome', models.CharField(blank=True, max_length=160)),
                ('observacao', models.TextField(blank=True)),
                ('retry_solicitado_em', models.DateTimeField(blank=True, null=True)),
                ('retry_processado_em', models.DateTimeField(blank=True, null=True)),
                ('instalacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='pdv.instalacaopdvoffline')),
            ],
            options={
                'db_table': 'pdv_ocorrencias_offline',
                'ordering': ['status', '-vista_por_ultimo_em'],
                'indexes': [models.Index(fields=['status', '-vista_por_ultimo_em'], name='pdv_ocor_status_visto_idx'), models.Index(fields=['retry_solicitado_em'], name='pdv_ocor_retry_idx')],
                'constraints': [models.UniqueConstraint(fields=('instalacao', 'local_id'), name='uniq_pdv_ocorrencia_inst_local')],
            },
        ),
    ]
