# Generated by Django 5.2.17 on 2026-09-25 17:55

import apps.pdv.models.rota_delivery
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_parametrossistema_balanca_ean'),
        ('pdv', '0027_instalacaopdvoffline_armazenamento_persistente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaDeliveryPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.pdv.models.rota_delivery.gerar_token_rota_delivery, editable=False, max_length=32, unique=True)),
                ('pedido_ids', models.JSONField(blank=True, default=list)),
                ('entregador', models.CharField(blank=True, max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rota_delivery_publica', to='core.filial')),
            ],
            options={
                'verbose_name': 'Rota pública de delivery',
                'verbose_name_plural': 'Rotas públicas de delivery',
                'db_table': 'pdv_rotas_delivery_publicas',
            },
        ),
    ]
