# Generated by Django 5.2.17 on 2026-08-25 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualidade", "0003_parametroqualidadecategoria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemAnalise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_parametro", models.CharField(max_length=60)),
                ("unidade_medida", models.CharField(blank=True, max_length=10)),
                (
                    "valor_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("obrigatorio", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("valor_texto", models.CharField(blank=True, max_length=160)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Não conferido"),
                            ("conforme", "Conforme"),
                            ("nao_conforme", "Não conforme"),
                            ("nao_aplica", "Não se aplica"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=14,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=300)),
                (
                    "acao_corretiva",
                    models.TextField(
                        blank=True,
                        help_text="O que foi feito — não a categoria, a ação.",
                    ),
                ),
                ("acao_em", models.DateTimeField(blank=True, null=True)),
                (
                    "acao_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_corretivas_qualidade",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="qualidade.analisequalidade",
                    ),
                ),
                (
                    "parametro",
                    models.ForeignKey(
                        blank=True,
                        help_text="O cadastro que originou esta linha, quando ainda existe.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_analise",
                        to="qualidade.parametroqualidadeproduto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da análise",
                "verbose_name_plural": "Itens da análise",
                "db_table": "analises_qualidade_itens",
                "ordering": ["analise", "ordem", "nome_parametro"],
                "indexes": [
                    models.Index(
                        fields=["analise", "situacao"],
                        name="analises_qu_analise_30a953_idx",
                    ),
                    models.Index(
                        fields=["situacao"], name="analises_qu_situaca_4f77f7_idx"
                    ),
                ],
            },
        ),
    ]
