# Generated by Django 5.2.17 on 2026-10-01 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0016_analise_custo_compra'),
        ('core', '0075_parametrossistema_balanca_ean'),
        ('produtos', '0041_produto_agendavel_produto_duracao_servico_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pessoa_atendida_nome', models.CharField(max_length=150)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fim', models.DateTimeField(db_index=True)),
                ('fim_com_intervalo', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando confirmação'), ('confirmado', 'Confirmado'), ('chegou', 'Cliente chegou'), ('em_atendimento', 'Em atendimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('nao_compareceu', 'Não compareceu')], db_index=True, default='confirmado', max_length=24)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('whatsapp_nao_oficial', 'WhatsApp não oficial'), ('whatsapp_oficial', 'WhatsApp oficial'), ('link', 'Link de agendamento')], default='manual', max_length=24)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='cadastros.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
            ],
            options={
                'db_table': 'agenda_agendamentos',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=150)),
                ('duracao_minutos', models.PositiveSmallIntegerField()),
                ('intervalo_minutos', models.PositiveSmallIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='agenda.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
            ],
            options={
                'db_table': 'agenda_agendamento_itens',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervalo_padrao_minutos', models.PositiveSmallIntegerField(default=0)),
                ('cor', models.CharField(default='#2563eb', max_length=7)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_agenda', to='cadastros.funcionario')),
            ],
            options={
                'db_table': 'agenda_profissionais',
                'ordering': ['funcionario__nome'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fim', models.DateTimeField(db_index=True)),
                ('motivo', models.CharField(max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('profissional', models.ForeignKey(blank=True, help_text='Em branco, bloqueia toda a filial.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='agenda.profissionalagenda')),
            ],
            options={
                'db_table': 'agenda_bloqueios',
                'ordering': ['inicio'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.profissionalagenda'),
        ),
        migrations.CreateModel(
            name='ProfissionalServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_vinculados', to='agenda.profissionalagenda')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais_vinculados', to='produtos.produto')),
            ],
            options={
                'db_table': 'agenda_profissionais_servicos',
            },
        ),
        migrations.AddField(
            model_name='profissionalagenda',
            name='servicos',
            field=models.ManyToManyField(related_name='profissionais_agenda', through='agenda.ProfissionalServico', to='produtos.produto'),
        ),
        migrations.CreateModel(
            name='JornadaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('pausa_inicio', models.TimeField(blank=True, null=True)),
                ('pausa_fim', models.TimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='agenda.profissionalagenda')),
            ],
            options={
                'db_table': 'agenda_jornadas',
                'ordering': ['dia_semana', 'inicio'],
                'constraints': [models.UniqueConstraint(fields=('profissional', 'dia_semana'), name='agenda_jornada_dia_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['filial', 'profissional', 'inicio'], name='agenda_agen_filial__00e22a_idx'),
        ),
        migrations.AddConstraint(
            model_name='profissionalservico',
            constraint=models.UniqueConstraint(fields=('profissional', 'servico'), name='agenda_profissional_servico_unico'),
        ),
        migrations.AddConstraint(
            model_name='profissionalagenda',
            constraint=models.UniqueConstraint(fields=('filial', 'funcionario'), name='agenda_profissional_filial_unico'),
        ),
    ]
