# Generated by Django 5.2.17 on 2026-10-01 16:50

import apps.agenda.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_reparar_schema_tenant'),
        ('core', '0075_parametrossistema_balanca_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaLinkPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.agenda.models.gerar_token_agenda, editable=False, max_length=64, unique=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('filial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_agenda_publica', to='core.filial')),
            ],
            options={
                'db_table': 'agenda_links_publicos',
            },
        ),
    ]
